### ISSUE TITLE
Add the ability to add a secondary Gemfile (that can be global to the system for example)

### ISSUE THREAD

**Issue by carllerche** [bundler/bundler#183]
- the information in the secondary gemfile are lower priority
- Do not include the secondary gemfile in a lock
- the secondary Gemfile should not effect the resolve of the main Gemfile. It is a superset on top of it.
- Add the ability to specify this secondary gemfile with an ENV variable, .bundle/config, or flag.

**Comment by CodyBrouwers** [comment]
For anyone that ends up coming across this thread here what I've done, that seems to work but does still have one flaw:

1. Create a Gemfile.local file and add:
   ```ruby
   # Include the regular Gemfile
    eval File.read('Gemfile')
   ```
2. Add any other gems you want to use to the ` group :development[, :test]` (I wouldn't suggest doing this for any other environment)
3. Run `bundle install --gemfile=Gemfile.local`
4. You will now have a Gemfile.local.lock
5. You can now use the gem by running `BUNDLE_GEMFILE=Gemfile.local bundle exec {{gem command}}`
6. Or to make Bundler prioritize Gemfile.local gems, you can specify in `{{app root}}/.bundle/config`:
    `BUNDLE_GEMFILE: "Gemfile.local"`

The flaw in this is that since there are two Gemfile lock files, there isn't a way to ensure consistent versions between the two so something to aware of. You can at least check for inconsistencies by not adding any additional gems to the Gemfile.local and comparing the two lock files, so it's not a dealbreaker for me.

**Comment by indirect** [comment]
Thanks for reporting back! I'm glad you've found something that works for your needs. 👍

**Comment by rlue** [comment]
> The flaw in this is that since there are two Gemfile lock files, there isn't a way to ensure consistent versions between the two so something to aware of. 
I use the following bash function to keep my lockfiles in sync:

```bash
function bundle() {
  bundle="$(type -P bundle)"

  if [ -r "$BUNDLE_GEMFILE" ] && [ -r Gemfile ] &&
     [ "$BUNDLE_GEMFILE" != Gemfile ] && 
     [[ "$1" =~ ^(|install|update)$ ]]; then 
    BUNDLE_GEMFILE=Gemfile "$bundle" "$@"
    cp Gemfile.lock "${BUNDLE_GEMFILE}.lock"
  fi

  "$bundle" "$@"
}
```

**Comment by bmulholland** [comment]
@rlue Thanks for that. I created a slight modification to support using a custom gemfile in some projects on the same machine but not others. This just means using the value from `bundle config`, if present, instead of an environment variable. Use `bundle config --local gemfile Gemfile.local` to set it for this project only.

```
function bundle() {
  bundle="$(type -P bundle)"

  gemfile=$BUNDLE_GEMFILE

  if [ -z "$gemfile" ]; then
    gemfile=`bundle config gemfile --parseable | sed -e 's/^gemfile=//'`
  fi

  if [ -r "$gemfile" ] && [ -r Gemfile ] &&
     [ "$gemfile" != Gemfile ] && 
     [[ "$1" =~ ^(|install|update)$ ]]; then 
    BUNDLE_GEMFILE=Gemfile "$bundle" "$@"
    cp Gemfile.lock "${gemfile}.lock"
  fi

  "$bundle" "$@"
}
```

**Comment by rlue** [comment]
@bmulholland I tried this, but faced a strange bug:

When `Gemfile.local` is specified in the `BUNDLE_GEMFILE` environment variable, then

    BUNDLE_GEMFILE=Gemfile bundle install

successfully updates `Gemfile.lock`.

When it's set in `.bundle/config`, however, that command does not update `Gemfile.lock`, so I'll be sticking to environment variables for now.

(In fact, this probably deserves an issue of its own.)

**Comment by bmulholland** [comment]
@rlue That's odd - it's working for me. Bundler 1.16.1. Make sure your BUNDLE_GEMFILE environment variable is NOT set, since that will necessarily override the setting in `bundle config`.

**Comment by andretf** [comment]
I'm using this aliases in my `.zshrc`:

    alias be="bundle exec"
    alias bel="BUNDLE_GEMFILE=Gemfile.local be"
    alias bei="bundle && BUNDLE_GEMFILE=Gemfile.local bundle"
---
    $ bei
    $ bel guard

working good..
