### ISSUE TITLE
Feature proposal: Bundler "distro mode"

### ISSUE THREAD

**Issue by bkabrda** [bundler/bundler#2004]
Hi,
as per discussion at #1964, I'd like to propose a patch [1], that introduces a bundler "distro mode". The idea is simple and taken from RubyGems library. If file defaults/operating_system.rb is present, it is loaded (unless switched off by env variable). It can define (so far) a method distro_modify, that alters a list of matching_versions when doing bundle install/update.
- If the file is not present or the behaviour is switched off by env variable, bundler's behaviour is not modified in any way.
- If the file is present and the behaviour is not switched off, it prints out a message that bundler is running in a distro mode and uses the distro_modify method.
- The implementation of defaults/operating_system.rb is left to a distro packager.

Would this patch be acceptable for you? If no, is there some kind of modification I could do to make it acceptable?

Thanks a lot!

[1] https://gist.github.com/3009644

**Comment by akostadinov** [comment]
As a user I find it highly annoying that a simple switch patch has been rejected by bundle because of some personal opinion. I don't want bundle to decide instead of me how dependencies should be resolved.
My personal opinion is that I trust my distro maintainers more than upstream to keep me updated with security without introducing compatibility issues.  I don't mind other people to have a different view but why such switch should not be allowed into bundle?
