### ISSUE TITLE
Way to bundle update conservatively a single gem

### ISSUE THREAD

**Issue by marcandre** [bundler/bundler#2016]
If `some_gem` is already installed, and I want the latest version of it, `bundle install` will not do anything and `bundle update some_gem` will update `some_gem` (_yay!_) but also any of its dependency (_not what I want_). I'd rather not update my rails version just because I'm also updating a minor gem that has rails as a dependency.

Only current way is to go in the Gemfile and manually state that we want a version `>= current_version`, and now `bundle install` will update it.

It would be awesome to be able to update `some_gem` and be conservative for the rest, without having to state an actual version in the Gemfile.

BTW, I don't understand the reason behind the decision that `bundle update foo` is not conservative; this won't happen when I bundle install and have added `some_gem` line in my Gemfile, or increased the minimum version for that gem. In any case, a `--conservative` or something would be greatly appreciated.

This is a repost of #2011

**Comment by jonswar** [comment]
+1 for this request. We do very conservative gem updates in our environment so it's always a surprise when bundler updates dependencies unnecessarily!

**Comment by vassilevsky** [comment]
`--conservative`: update to the latest version; update dependencies only if necessary

`--ultra-conservative`: update to the maximum possible version still satisfied by current dependencies

**Comment by drewbug** [comment]
:+1:

**Comment by gerrywastaken** [comment]
> That also sounds very, very hard to get right. :)

@indirect What are the difficult parts with @marcandre's suggestion? Where `bundle update 'foo'` is really:

> Run bundle install with a temporary requirement gem 'foo', 'max.version.found'

**Comment by pjscopeland** [comment]
@indirect, 6 Jul 2012
> If you need to update just one gem to a specific version, that is when you should edit your Gemfile and then run bundle install (which will re-resolve your Gemfile in the most conservative mode).

Er... no. I am updating `rails` from 4.2.0 to 4.2.5, and `test_after_commit` from 0.4.0 to 0.4.2. Here are the changes to my Gemfile (minimised a bit):

```
$ git diff
-gem 'rails', '4.2.0'
+gem 'rails', '4.2.5'
-gem 'test_after_commit', '0.4.0'
+gem 'test_after_commit', '0.4.2'
```

And then, according to your instructions, I'm supposed to run:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
You have requested:
  rails = 4.2.5

The bundle currently has rails locked at 4.2.0.
Try running `bundle update rails`
```

So that doesn't work. If I do `bundle update rails test_after_commit`, the following gems are the ones that get upgraded. However, only the bold changes are actually needed to satisfy my new requirements:
- **actionmailer (4.2.5)**
- **actionpack (4.2.5)**
- **actionview (4.2.5)**
- **activejob (4.2.5)**
- **activemodel (4.2.5)**
- **activerecord (4.2.5)**
- **activesupport (4.2.5)**
- arel (6.0.3)
- globalid (0.3.6)
- loofah (2.0.3)
- mime-types (2.99)
- mini_portile2 (2.0.0)
- minitest (5.8.3)
- nokogiri (1.6.7)
- **rails (4.2.5)**
- rails-dom-testing (1.0.7)
- **railties (4.2.5)**
- sprockets (3.4.1)
- sprockets-rails (2.3.3)
- **test_after_commit (0.4.2)**

I don't want all the rest! I had to manually figure out in each case whether the change was actually needed, and then revert parts of my `Gemfile.lock`. It would be *so* much easier if I could just run `bundle update rails --conservative`! (`--minimal` was the word I thought of.)

**Comment by indirect** [comment]
@pjscopeland you should be able to get that exact behavior today by running `bundle install --source rails`. It's a bug, but it's a useful big, and we'll make sure it keeps working until we replace it with a feature with the same behavior.

**Comment by hashar** [comment]
Well `--source` does not work at all:
```
$ bundle --version
Bundler version 1.11.2
$ bundle install --source foo
Unknown switches '--source'
```

And `bundle update --source foo` still update dependencies of foo even when the ones in the .lock file match...

**Comment by jbodah** [comment]
> And bundle update --source foo still update dependencies of foo even when the ones in the .lock file match...

For what it's worth I'm not getting that behavior with 1.11.2. `--source` still seems to work for me

```
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle -v
Bundler version 1.11.2
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 10.3.2
Using hitimes 1.2.2
Using coderay 1.1.0
Using multi_json 1.10.1
Using mime-types 2.4.3
Using netrc 0.8.0
Using docile 1.1.5
Using simplecov-html 0.8.0
Using tins 1.3.3
Using thor 0.19.1
Using ffi 1.9.6
Using formatador 0.2.5
Using rb-fsevent 0.9.4
Using lumberjack 1.0.9
Using method_source 0.8.2
Using slop 3.6.0
Using minitest 5.4.3
Using bundler 1.11.2
Using timers 4.0.1
Using rest-client 1.7.2
Using simplecov 0.9.1
Using term-ansicolor 1.3.0
Using rb-inotify 0.9.5
Installing pry 0.10.1
Using minitest-server 1.0.2
Using celluloid 0.16.0
Using coveralls 0.7.1
Using minitest-bisect 1.3.0
Using listen 2.7.11
Using guard 2.6.1
Using guard-minitest 2.3.2
Bundle complete! 6 Gemfile dependencies, 31 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle -v
Bundler version 1.11.2
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle update --source rake
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.5.0 (was 10.3.2)
Using hitimes 1.2.2
Using coderay 1.1.0
Using multi_json 1.10.1
Using mime-types 2.4.3
Using netrc 0.8.0
Using docile 1.1.5
Using simplecov-html 0.8.0
Using tins 1.3.3
Using thor 0.19.1
Using ffi 1.9.6
Using formatador 0.2.5
Using rb-fsevent 0.9.4
Using lumberjack 1.0.9
Using method_source 0.8.2
Using slop 3.6.0
Using minitest 5.4.3
Using bundler 1.11.2
Using timers 4.0.1
Using rest-client 1.7.2
Using simplecov 0.9.1
Using term-ansicolor 1.3.0
Using rb-inotify 0.9.5
Using pry 0.10.1
Using minitest-server 1.0.2
Using celluloid 0.16.0
Using coveralls 0.7.1
Using minitest-bisect 1.3.0
Using listen 2.7.11
Using guard 2.6.1
Using guard-minitest 2.3.2
Bundle updated!
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle update --source pry
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.5.0
Using hitimes 1.2.2
Using coderay 1.1.0
Using multi_json 1.10.1
Using mime-types 2.4.3
Using netrc 0.8.0
Using docile 1.1.5
Using simplecov-html 0.8.0
Using tins 1.3.3
Using thor 0.19.1
Using ffi 1.9.6
Using formatador 0.2.5
Using rb-fsevent 0.9.4
Using lumberjack 1.0.9
Using method_source 0.8.2
Using slop 3.6.0
Using minitest 5.4.3
Using bundler 1.11.2
Using timers 4.0.1
Using rest-client 1.7.2
Using simplecov 0.9.1
Using term-ansicolor 1.3.0
Using rb-inotify 0.9.5
Installing pry 0.10.3 (was 0.10.1)
Using minitest-server 1.0.2
Using celluloid 0.16.0
Using coveralls 0.7.1
Using minitest-bisect 1.3.0
Using listen 2.7.11
Using guard 2.6.1
Using guard-minitest 2.3.2
Bundle updated!
```

```
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ bundle -v
Bundler version 1.11.2
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
Bodah@jbodah-local 2.1.3p242 ~/repos/spy_rb (master) $ gem -v
2.4.8
```

**Comment by indirect** [comment]
Sorry, it's `update --source foo`.

**Comment by indirect** [comment]
Here's an explanation of how --source updating works: http://ilikestuffblog.com/2012/07/01/you-should-update-one-gem-at-a-time-with-bundler-heres-how/

**Comment by hashar** [comment]
Yup found that.  Though `bundle update --source foo` still have the dependencies of `foo`  re-resolved even when matched which is not that conservative.  That is a different story though. Thank you for the tip about `--source`.

**Comment by chrismo** [comment]
I've been messing around with this for a while, just released 0.7.0 of a gem today, would love feedback: https://github.com/livingsocial/bundler-patch

**Comment by jrochkind** [comment]
An old ticket, but a ways back @indirect [says](https://github.com/bundler/bundler/issues/2016#issuecomment-6786701):

> If you need to update just one gem to a specific version, that is when you should edit your Gemfile and then run bundle install (which will re-resolve your Gemfile in the most conservative mode).

That's how I thought it worked, and I swear it's worked this way for me before (maybe back in 2012), but today it does not seem to. I edit my `Gemfile` changing a Rails dependency from `~> 4.1` to `~> 4.2`, then run `bundle install`, and get:

~~~
You have requested:
  rails ~> 4.2

The bundle currently has rails locked at 4.1.14.1.
Try running `bundle update rails`
~~~

This surprised me. Of course, if I run `bundle update rails`, potentially more things then I want will be updated.  Are things still supposed to work like @indirect says?

Of course, this case may be complicated by the fact that "rails" has it's own dependencies, on activerecord etc, that of course will need to be updated too to get a resolution. But I thought this had worked for me before. 

Anyone know what's up?

**Comment by chrismo** [comment]
@jrochkind I couldn't recreate with just a simple Gemfile with just gem 'rails' in it ... but that's not valid, the regular Gemfile would need to be considered. Anything you can link to in a gist?

**Comment by chrismo** [comment]
Bundler now has some new flags for conservative updates, would love y'alls feedback: https://github.com/bundler/bundler-features/issues/122

**Comment by jrochkind** [comment]
@chrismo I don't have a simple repro, sorry, these things tend to occur in complicated gem files. And I think I've lost the gemfile/gemfile.lock that happened in, don't remember what product anymore either. 

But I have had this problem fairly regularly. Next time it happens, is it useful if I file a fresh issue, with the complete Gemfile/Gemfile.lock even if it's complicated?

What keeps me from filing in the past is not even being sure if what I'm seeing is somehow expected behavior (in the past, there have been things I was sure were rubygems bugs, that I was told was not a bug upon reporting), or not having any idea if such reports are welcome and will get any attention at all.

**Comment by chrismo** [comment]
Yeah, definitely. Happy to try and diagnose a weird case. 👻

**Comment by jrochkind** [comment]
@chrismo Okay if it happens again, I'll file an issue! So long as we are agreed that the expected/intended behavior is:

> If you need to update just one gem to a specific version, that is when you should edit your Gemfile and then run bundle install (which will re-resolve your Gemfile in the most conservative mode).

I have to admit I don't understand what the docs at bundler/bundler-features#122 are describing, and I'm not sure if it's what others (and me) were actually wanting? Am I just not following the docs, or is it intended to be something differnet from what this issue is asking for?

What this issue is asking for is related to the quote above, originally from indirect. 

Consider a Gemfile with lots of things in it, including `'widget', '~> 4.3'`.  But let's say there's a Widget 5.2.0 out. If I manually update my Gemfile to `'widget', '~> 5.2'` and then run `bundle install` then what happens (or at least what we think is supposed to happen), is `widget` is updated to latest `5.2.0`, but widgets dependencies are _only_ updated _as neccesary to be compatible_ with 5.2.0.  Other widget dependencies whose Gemfile.lock versions are still compatible with the new 5.2.0 are _not_ updated. (This is very different than what happens when you run `bundle update widget`, where _all_ dependencies of widget are updated to latest possible version). 

What this issue is asking for is something similar, but without having to manually update the Gemfile. perhaps `bundle update --conservative widget` would find the most recent version of widget that exists, then resolve the rest of the dependencies _as if_ that version had been specified in the `Gemfile` (it is not though).  Since bundler can already do that (sans bugs) with a manual update of `Gemfile` and `bundle install`, it seems like the logic already exists?

Of course it gets more complicated if more than one gem is involved `bundle update --conservative widget gadget`.  But I could spec out what I'd want that to do too. 

But it's not clear to me that bundler/bundler-features#122 is describing anything like this at all. It appears to be something different, involving minor/patch restrictions, which is not what this issue was asking for, and is not something that to me is obviously useful for my workflow anyway.

**Comment by chrismo** [comment]
Thx for the feedback, it's exactly the sort of stuff I was hoping we could flush out at this stage. "Conservative updates" appears to have varying meaning to folks and your reply plus the comments on 122 from yesterday are already drawing out some additional use cases that weren't at the forefront of my mind when I wrote what I did.

If you're cool with it, I'd like to move this discussion over to that issue, so we can try to accumulate discussion there. I'm also curious if the existing comments there overlap with how you'd like things to work.

**Comment by codyrobbins** [comment]
I just ran into the exact problem that the original comments on this thread were describing: I had a very old project that needed a single gem updated to its latest version to pull in a fix for a bug in that gem, but every combination of `bundle install` and `bundle update gem-name-here` I tried resulted in almost every gem in the project getting updated. The gem that needed to be updated had no dependencies and for the sake of maintaining the status quo I did not want any other gems updated since they didn’t need to be. I just tried the `--minor` option to `bundle update` described in bundler/bundler-features#122 and it worked perfectly and did exactly what I needed! Thank you for implementing this!
