### ISSUE TITLE
Bundler could not find compatible versions for gem "bundler"

### ISSUE THREAD

**Issue by elf-pavlik** [bundler/bundler#2081]
I find this issue very confusing :(

while setting up: https://github.com/sharetribe/sharetribe

```
$ bundle install
```

works with fresh repo, but if in Gemfile i just uncomment

```
gem 'unicorn'
```

then running

```
$ bundle install
```

throws

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 3.0.0) ruby depends on
      bundler (~> 1.0.0) ruby

  Current Bundler version:
    bundler (1.1.5)

This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

**Comment by champsatin** [comment]
Hi, 

Can you please help me with this error :
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 3.0.1) ruby depends on
      bundler (~> 1.0.0) ruby

  Current Bundler version:
    bundler (1.9.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 1.0.0) ruby', which is required by gem 'rails (= 3.0.1) ruby', in any of the sources.

**Comment by indirect** [comment]
Update to a newer version of Rails.

**Comment by champsatin** [comment]
Thanks for the response. I tried "gem update rails"  & got the following error :-
Updating installed gems
ERROR:  While executing gem ... (Net::HTTPFatalError)
    503 "Service Unavailable"

Also on running "rails -v", I get the following o/p -

/home/champsatin/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate rails-3.0.1, because bundler-1.9.2 conflicts with bundler (~> 1.0.0) (Gem::ConflictError)
	from /home/aspire/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1280:in `activate'
	from /home/aspire/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from <internal:prelude>:10:in `synchronize'
	from /home/aspire/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /home/aspire/.rvm/gems/ruby-1.9.3-p551@rails3tutorial/bin/rails:22:in `<main>'
	from /home/aspire/.rvm/gems/ruby-1.9.3-p551@rails3tutorial/bin/ruby_executable_hooks:15:in `eval'
	from /home/aspire/.rvm/gems/ruby-1.9.3-p551@rails3tutorial/bin/ruby_executable_hooks:15:in `<main>'

Can you please help.

**Comment by segiddins** [comment]
@champsatin you need to update the rails dependency in your Gemfile to be something newer than `3.0.1`

**Comment by saydulk** [comment]
bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all
non-root users on this machine.
Ignoring executable-hooks-1.3.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.2.7
Ignoring nio4r-2.1.0 because its extensions are not built. Try: gem pristine nio4r --version 2.1.0
Ignoring nokogiri-1.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.1
Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
Fetching https://github.com/rails-api/active_model_serializers.git
Fetching https://github.com/instructure/nokogiri-xmlsec-me-harder.git
Fetching https://github.com/kreynolds/cassandra-cql.git
Fetching https://github.com/twitter/thrift_client.git
Fetching https://github.com/ccutrer/redis-store.git
Fetching https://github.com/instructure/test-queue.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (<= 1.16.0, >= 1.13.3)

  Current Bundler version:
    bundler (1.16.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.16.0, >= 1.13.3)' in any of the relevant sources:
  the local ruby installation
![screenshot from 2017-12-27 13 54 15](https://user-images.githubusercontent.com/1058663/34374841-71364bbc-eb0d-11e7-8fd3-9977b3a36598.png)

**Comment by thonsun** [comment]
so what is the way to solve this problem

**Comment by ahujasushant** [comment]
@thonsun can you show your `Gemfile`?
