### ISSUE TITLE
Deployment fails when using paths in Gemfile

### ISSUE THREAD

**Issue by wildchild** [bundler/bundler#2175]
```ruby
gem "my-gem", path => "../../my-gem"
```

after running bundle package --all && bundler install --local Gemfile.lock contains new path -- "vendor/cache/my-gem"

Gemfile still contains old path as expected.

bundle install --deployment will end with:

<pre>
You have added to the Gemfile:
* source: source at ../../my-gem

You have deleted from the Gemfile:
* source: source at vendor/cache/my-gem

You have changed in the Gemfile:
* couchrest from `source at ../../my-gem` to `no specified source`
</pre>

Is it normal behavior and I must edit paths in Gemfile on deployment?

**Comment by kowal** [comment]
Hi

I've just run into this. Gems specified via ```:path``` aren't vendored by ```bundle package --all```.

Docs say:
"--all: package :git, :path, and .gem dependencies. Once used, the --all option will be remembered."

Does it really make sense to use gems from "path" locations and then package them in vendor/cache to be used in bundle --local or --deployment scenarios?

Or maybe instead I should simply add those gems manually to ```vendor/cache``` and in Gemfile specify them without ```path```. But then - what happens when someone on other machine runs ```bundle install``` without ```--local```?

**Comment by danbob** [comment]
I've also had to deal with this. `bundle package --all` adds the gem directories to `vendor/cache`, `Gemfile.lock` gets updated with the `vendor/cache` paths, but running `bundle install --deployment` on the server gives me the same errors as in the original report.

As a workaround, I changed the line in my `Gemfile` to this:
```ruby
    gem 'shared', path: Pathname.new('../shared').exist? ? '../shared' : 'vendor/cache/shared'
```

**Comment by LynnCo** [comment]
This issue is open for anyone to start working on a PR for

**Comment by allenzhao** [comment]
I'm working on it;)
