### ISSUE TITLE
Invalid platforms should be warned about only

### ISSUE THREAD

**Issue by p** [bundler/bundler#2428]
Getting this error:

<pre>
rvm@reactor ruby-bitly % bundle install
`ruby_20` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :mri, :mri_18, :mri_19, :rbx, :jruby, :mswin, :mingw, :mingw_18, :mingw_19]
</pre>

This should be a warning. If the platform bundler runs on is recognized, what does failing achieve when additional unknown platforms are specified?

**Comment by azul** [comment]
Worked around this with:
```ruby
  if Bundler::current_ruby.respond_to? :mri_21?
    gem 'byebug', :platforms => [:mri_20, :mri_21]
  end
```

**Comment by rbu** [comment]
This is absurd. We try to keep our Gemfile portable between Ruby versions (by specifying different dependencies based on platform) and we end up breaking it for old systems because their bundler would need an update (even though their Ruby is ancient). Considering that bundler comes as a OS system package, it is infeasible to update locally.

Worst of all, this happens in a tool designed to lock up existing versions so that you don't break when the world of dependencies moves forward?

**Comment by indirect** [comment]
@rbu Hi. First, I need to point out that Bundler has a code of conduct, and you are violating it. This is your single warning, and if you decide to continue to be a jerk on this tracker, you'll be banned.

With that said, thanks for the feedback. Forwards compatibility is valuable, but very tricky to get right. Bundler has historically focused on perfect backwards compatibility, without nearly as much effort going to forwards compatibility with future versions. We'll get better at forwards compatibility as time goes on and we have more experience with it.

**Comment by dwt** [comment]
Out of interest, reading the code of conduct it seems to be very explicit in forbidding any language that says 'you are dumb' (or similar ad hominem) but is very explicit not to forbid 'this solution is absurd'.

To me this makes a lot of sense, because one is ad hominem (and dumb) and the other is necessary to have an open discourse about the merit of different technical approaches.

**Comment by rbu** [comment]
Apologies, I did not mean to offend. Would you explain which part of my statement you took offense with so that I don't repeat it?

To the point, I understand it's difficult to anticipate future developments and prepare forward compatibility and I completely agree in most cases one should rather print an explicit assertion and fail. However, as others before pointed out, I would suggest unknown platforms can safely be ignored.

Let me finally share our workaround:
```ruby
two_and_up = [:mri_20, :mri_21, :mri_22, :mri_23, :mri_24] & Bundler::Dsl::VALID_PLATFORMS

gem 'debugger', :require => 'ruby-debug', :platforms => [:mri_19]
gem 'byebug', :platforms => two_and_up
```

**Comment by p** [comment]
Interesting, is `Bundler::Dsl::VALID_PLATFORMS` part of bundler's public API which is guaranteed to never change?

**Comment by segiddins** [comment]
@p no, that constant is private API -- use it at your own risk, it may change in the future

**Comment by p** [comment]
Going back to the original bug report, the problem was in a third party library-bundler interaction. Changing said library to use bundler internals is not a usable solution in that case (if I was to make this change locally I would just delete the offending platform instead).
