### ISSUE TITLE
bundle install --binstubs clobbers the projects existing bin/ executables

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#2838]
I noticed that `bundle install --binstubs` overwrites the project's existing `bin/` executables.

```
$ bundle install --binstubs
$ git diff bin/
diff --git a/bin/ronin b/bin/ronin
index 3abc2d5..4112e15 100755
--- a/bin/ronin
+++ b/bin/ronin
@@ -1,20 +1,16 @@
 #!/usr/bin/env ruby
+#
+# This file was generated by Bundler.
+#
+# The application 'ronin' is installed as part of a gem, and
+# this file is here to facilitate running it.
+#

-require 'rubygems'
-
-root = File.expand_path(File.join(File.dirname(__FILE__),'..'))
-if File.directory?(File.join(root,'.git'))
-  Dir.chdir(root) do
-    begin
-      require 'bundler/setup'
-    rescue LoadError => e
-      warn e.message
-      warn "Run `gem install bundler` to install Bundler"
-      exit -1
-    end
-  end
-end
+require 'pathname'
+ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
+  Pathname.new(__FILE__).realpath)

-require 'ronin/ui/cli'
+require 'rubygems'
+require 'bundler/setup'

-Ronin::UI::CLI.start
+load Gem.bin_path('ronin', 'ronin')
```

**Comment by darrellnash** [comment]
I'm sorry, I know this issue is nearly 4 years old (and closed), but I just got bitten by it, and it doesn't seem like there's a new way to do it (v2 doesn't look like it's in development).

Couldn't we add a backward-compatible new option to `bundle install` like `--no-clobber` that would allow those of us who rely on the `bundle install --binstubs` to fill in the rest of executables during deployment that won't overwrite already deployed files?

**Comment by dcorking** [comment]
This also occurs with Bundler 2.

Even a supposedly simple "bundle update --bundler" (from 1.17.2 to 2.0.1) clobbers Rails binstubs. I am now nervous about distributing my application, in case other users end up with different binstubs than the ones in the git repo.

Are you interested in re-opening this feature request and tagging it for version 3.0?
