### ISSUE TITLE
Use `rspec --init` to generate skeleton files for gems using rspec

### ISSUE THREAD

**Issue by myronmarston** [bundler/bundler#3035]
I just learned about the `-t` option to `bundle gem`.  `rspec --init` similarly generates the skeleton files for using RSpec on a project.  Would you be open to using `rspec --init` instead of your own templates?  The files generated by `rspec --init` include more settings for a good out-of-the-box experience:

https://github.com/rspec/rspec-core/blob/a944fbfe7cd2ff6557d962b85f98c2494919a640/lib/rspec/core/project_initializer/dot_rspec

https://github.com/rspec/rspec-core/blob/a944fbfe7cd2ff6557d962b85f98c2494919a640/lib/rspec/core/project_initializer/spec_helper.rb

**Comment by LynnCo** [comment]
@e2 likely had other code to write, so anyone can work on a PR for this

(assuming the feature wasn't added in already)

**Comment by segiddins** [comment]
Looks like we already use rspec 3...

**Comment by e2** [comment]
FWIW, the template locks to RSpec 3.0 since: https://github.com/bundler/bundler/commit/1691f6ab287d047913b9cee3c25e7e2493311034

The spec_helper file generated by `rspec --init` hasn't changed since v3.0.3.

Personally, I use *most* of the commented out options there. The benefit is having a decent default "cheetsheet" of options. I actually would prefer the options to be less "documented" there and more of them commented out by default.

I see 2 "reasonable" options:

1. Include a url to a decent "RSpec starter template" inside the minimalistic `spec_helper.rb` created by `bundle gem`
2. Show a warning from within the `spec_helper.rb` that RSpec isn't configured. This deserves a warning because newbie users are going to be missing out on useful features. E.g. the warning can tell the user to delete the generated file and run `rm -f spec/spec_helper.rb && bundle install && rspec --init`.

I'd prefer option 1, because it allows enabling more features by default. (`rspec --init` understandably has to be conservative with what it turns on).

On the flip side, I doubt a new gem will even have lots of tests to being with, so a "full-blow development environment" probably doesn't suit what `bundle gem` is supposed to help with. (Which is: just create something basic enough to push to RubyGems or a private gem server).

**Comment by myronmarston** [comment]
> The spec_helper file generated by rspec --init hasn't changed since v3.0.3.

It's changed several times since 3.0.3:

* `config.warnings = true` -- https://github.com/rspec/rspec-core/commit/c51d38ccdd39adcc8f5554c9324421e7be89d9b7 (included in 3.1.0)
* Multiple changes in https://github.com/rspec/rspec-core/commit/b5ea0e658cac04e42f28652c9e99b38167597407 (included in 3.1.0)
* `config.example_status_persistence_file_path = "spec/examples.txt"` -- https://github.com/rspec/rspec-core/commit/8ced2876e5fb5edac778b74cbc610586825d8b05 (included in 3.3.0)
* `config.filter_run_when_matching :focus` -- https://github.com/rspec/rspec-core/commit/7a238306fdcc693e16dcd430191f881c8c26db30 (will be included in the soon-to-be-released 3.5.0)

**Comment by indirect** [comment]
oh man, yes, we should get `example_status_persistence_file_path` into the default gem template, that makes things so much better. 👍 for adding tooling and a spec so that we ship the up-to-date spec helper.

**Comment by e2** [comment]
> It's changed several times since 3.0.3:

I only checked the diff between earliest and latest, to show that if Bundler included the template hard-coded from 3.0.3, it wouldn't need updating as of today to just work - and it would still be better than the default because of the documented options available for users to activate.

I'd set the constraint to '~> 3.4', because it's a waste of time to wonder if a given template will work on an earlier RSpec in this case.

The RSpec team already puts a **ton** of effort into making sure things work smoothly, so unless I'm missing something, installing RSpec 3.[0-3] instead of 3.4 makes no sense. Also, this way features and be enabled explicitly with default values - instead of commenting them out in a `=begin` `=end` section.

**Comment by segiddins** [comment]
I'm going to close this for now, but people can feel free to make PRs improving the skeleton files we generate, thanks for the lively discussion!
