### ISSUE TITLE
Fails to create symlinks in /usr/local/bin/ on OpenBSD

### ISSUE THREAD

**Issue by dt1973** [bundler/bundler#3355]
Getting `zsh: command not found: bundle` after `gem install bundler` on OpenBSD 5.7 because `/usr/local/bin/bundle22` doesn't get symlinked to `/usr/local/bin/bundle`. Had to do so manually. Can anyone else confirm this?

Download and install: ftp://ftp.openbsd.org/pub/OpenBSD/snapshots/amd64/install57.iso

Do ie. `export PKG_PATH=ftp://ftp.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/` and then `pkg_add ruby-2.2.0`.

**Comment by indirect** [comment]
I don't use BSD, so I can't really help with this, sorry.

**Comment by jeremyevans** [comment]
This is expected behavior with the OpenBSD ruby ports.  Note that the `gem` binary is installed on OpenBSD as `gem22` or `gem21`, and the user is expected to symlink manually to the preferred version (you must have done so, otherwise `gem install bundler` would have given you `command not found: gem`).  Likewise, gems installed via `gem22 install` on OpenBSD have their executables automatically suffixed.  Just like the main ruby executables, these should be manually symlinked to your preferred version.

**Comment by dt1973** [comment]
:+1:
