### ISSUE TITLE
Sources API receive gem names of other sources

### ISSUE THREAD

**Issue by sheerun** [bundler/bundler#3359]
Hey! I represent rails-assets.org service.

Given following Gemfile:

```ruby
gem 'bundler', '>= 1.7.0'

source 'https://rubygems.org' do
  gem 'rails', '4.0.0'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-sugar'
  gem 'rails-assets-angular'
end
```

We receive following request on `bundle install`:

```
GET "/api/v1/dependencies?gems=bundler,rails,rails-assets-sugar,rails-assets-angular"
```

Is it desired behavior? Shoudn't we receive only rails-assets gems?

**Comment by sheerun** [comment]
Or maybe the other way: is it OK that bundler sends 3rd party gem names to rubygems.org API?

**Comment by indirect** [comment]
While it _may_ be a bug that Bundler sends `rails` to `rails-assets.org`, it is definitely not a bug that Bundler sends `bundler` to both gem sources. Bundler deliberately asks all sources for any gem that is not locked to a single source, specifically so that it can print a warning if that gem is available from more than one source. For more information about sources, please see the [announcement of Bundler 1.7 and the sources security issue CVE-2013-0334](http://bundler.io/blog/2014/08/14/bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html).

**Comment by indirect** [comment]
I've created a [Trello ticket to reduce the requests for gem metadata](https://trello.com/c/gBqeGWpb), but most gems still need to be requested from most sources.
