### ISSUE TITLE
Bundler doesn't reinstall gem after changing its source

### ISSUE THREAD

**Issue by sheerun** [bundler/bundler#3360]
Hey! I represent rails-assets.org service.

We recently experienced security issue: someone [created](https://rubygems.org/gems/rails-assets-angular) gem on rubygems.org with the same name as on our service (rails-assets-angular), and changed source code by adding `alert("I'm in your app")`.

Until now we told our users to install rails-assets gems this way:

```ruby
source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails'
gem 'rails-assets-angular'
```

But after rails-assets-angular has been created on rubygems.org it started installing *instead* our gem.

We wanted to set things straight and instructed users to use following format:

```ruby
source 'https://rubygems.org'

gem 'bundler', '>= 1.7.0'

gem 'rails', '4.0.0'

source 'https://rails-assets.org' do
  gem 'rails-assets-angular'
end
```

But neither `bundle install` nor `bundle update` change a thing.. rails-assets-angular is still installed from rubygems repository. It's even still installed if I remove `Gemfile.lock` and issue `bundle install`.

**Comment by sheerun** [comment]
Bundler version 1.7.12

**Comment by indirect** [comment]
Bundler has no way to track where a gem came from once it is already installed, so I'm not even sure how to resolve this. Try running `bundle exec gem uninstall rails-assets-angular` before running `bundle install` again to re-install from the newly-added source.

**Comment by sheerun** [comment]
Yes, uninstalling malicious versions of gems manually solves the problem, but that is a poor solution ;/

This attack seems connected to [CVE-2013-0334](http://bundler.io/blog/2014/08/14/bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html). It works basically the same. Your resolution:

> The next time you run bundle install for any Gemfile that contains multiple sources, each gem available from multiple sources will print a warning.

Is OK, but I think in this case you **bundler shouldn't install gem from any source** (i.e. warning becoming an error). This would prevent installing malicious gem at first place..

I thought about warning users they don't use block source, but there's no way to tell it because bundler sends us all the gems, no matter whether they're in another source block or not (#3359).

I'm not sure how to solve this problem at point when malicious gem gets already installed.. It seems to install forever, even after changing sources, unless I uninstall it explicitly..

**Comment by iainbeeston** [comment]
Incidentally, (and for anyone reading this fix) a lot of platforms haven't upgraded to bundler 1.7 yet (heroku for example) and this fix won't work on them.

**Comment by indirect** [comment]
Since Bundler 1.6 does not and never will track what source gems are installed from, the only completely safe option is to upgrade to Bundler 1.7, fix every ambiguous gem warning, and then re-install every gem in the Bundle.




Uninstalling a single gem is not great, but it's what you can do today that will work.



Heroku has in fact upgraded to 1.7. Since this is  a security issue, please please upgrade to 1.7 and use source blocks where necessary.

**Comment by sheerun** [comment]
Even if someone uses 1.7, it's very likely he doesn't use source blocks.

So first time someone publishes malicious gem, user gets a warning, but gem is installed anyway.. And then only way to fix it is to uninstall gem manually. I think there are two solutions:

1. Include information in warning message how to re-install this gem
2. Stop installation instead showing warning on duplicated names. Force user to use source blocks.

**Comment by indirect** [comment]
I think adding instructions is a good idea. I'll work on a blog post talking about it as well.


There is no point in throwing an error, because if someone is upgrading, the gem will already be installed. It's impossible to "stop installation" if the user has ever run bundle install in the past.

**Comment by TimMoore** [comment]
> Stop installation instead showing warning on duplicated names. Force user to use source blocks.

I think we could add a flag to `bundle install` to make it error instead of warn on ambiguous sources, but there are some common scenarios where the same gem is legitimately in multiple sources, and I don't think we want to suddenly break things for those users. For example, when a team has forked a gem that is on rubygems.org and put their forked version in a private gem server.

It doesn't solve the problem of the gem already being installed, though.

BTW has anyone contacted the Rubygems help team about this? It seems like this would be a good case for force-yanking the gem on rubygems.org. That would at least stop this specific instance from getting worse.

**Comment by sheerun** [comment]
@TimMoore I've just posted relevant issue to rubygems repo: https://github.com/rubygems/rubygems.org/issues/857

**Comment by indirect** [comment]
In the future, we should track what source a gem has been installed from so that we can remove it and reinstall it when the source changes. I've created [a Trello card for that change](https://trello.com/c/kZtjlsld).
