### ISSUE TITLE
Why choose the Contributor Covenant CoC, and not other CoCs?

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3444]
It is a bit worrying that the bundler team choose to use the [Contributor Covenant CoC](http://contributor-covenant.org/version/1/0/0/) for the `CODE_OF_CONDUCT` file. Since bundler is _the_ defacto tool for generating new gems, this would make the Contributor Covenant CoC _the_ defacto contributor CoC. This seems a bit unfair to other CoCs (present and future). I may have missed something, but there didn't seem to be any public discussion about which (or any?) CoC to include. I feel as if the bundler core team are imposing their will on users without their consent.

**Comment by simi** [comment]
> I feel as if the bundler core team are imposing their will on users without their consent.

I feel the same.

But on the other side, now you're asked if you want to copy CoC ([with link to CCCoC](https://github.com/bundler/bundler/blob/master/lib/bundler/cli/gem.rb#L57-L63)) first time you're generating new gem with bundler and that option is remembered and used during next usage. I think that is fair enough.

**Comment by postmodern** [comment]
How can I use a different CoC? The answer is you can't. Either you opt-out and manually copy in your preferred CoC, or you opt-in to the CoC which bundler has chosen for you.

**Comment by indirect** [comment]
There was public discussion about codes of conduct that ended in a clear consensus: Bundler would disable all licenses and codes of conduct by default, and provide the MIT license and the Contributor Covenant as an option for those who want one or both.

The interactive prompts are only shown the first time a gem is generated, and they exist in order to explain the changes in rights that accompany adding the MIT license or adding the Contributor Covenant to your gems. The answers to the interactive prompts are saved in the user-level Bundler configuration, and used for any gems generated afterwards. The `gem` command provides `--[no-]mit` and `--[no-]coc` options to generate single gems with different options than the configured ones.

We won't be adding other CoCs, and we won't be adding more licenses. Many users (as in the consensus during public discussion of this issue) are satisfied with the simple gem generator offered by Bundler. Any developer who wants a more configurable gem generator is encouraged to use another project that is fully configurable, like Ore.

**Comment by simi** [comment]
You're asked if you want to use "Contributor Covenant CoC" (properly linked to its homepage). If you don't want to use "Contributor Covenant CoC", you can skip this and copy whatever CoC you'll need. But maybe that question is a little confusing.

**Comment by postmodern** [comment]
@indirect link to that discussion so I can catch up?

**Comment by indirect** [comment]
@postmodern https://github.com/bundler/bundler/pull/3305
