### ISSUE TITLE
Default Source

### ISSUE THREAD

**Issue by billywatson** [bundler/bundler#3528]
I think intelligent defaults are not only acceptable but a generally good practice.

I feel that if there are no sources in a Gemfile, that instead of raising an error, bundler should puts a warning message to STDOUT and then use https://rubygems.org instead of telling the human to put that in the gemfile and failing out.

If this is okay, I'd be happy to issue a pull request.

**Comment by indirect** [comment]
There is another use that I guess you haven't thought of, which is Gemfiles that only use local gems. We don't provide a default source so that isn't always clear where gems will come from, even if that means te gems only come from the local machine. If you don't like typing "source 'https://rubygems.org'", please run "bundle init" instead.

**Comment by TimMoore** [comment]
The other problem with an intelligent default is that you can never change it without breaking backward compatibility. For something like a `Gemfile`, explicit is the way to go.
