### ISSUE TITLE
Bundler updates gems when changing the source

### ISSUE THREAD

**Issue by jeroenj** [bundler/bundler#3540]
Tested with bundler 1.9.2 after https://github.com/bundler/bundler/issues/3520 was fixed.

Given a `Gemfile` with the following contents:

```ruby
source 'https://rubygems.org'
source 'https://private_gems.org'

gem 'public_gem'
gem 'private_gem', '~> 0.1'
```

where `private_gem` would be installed from the second gem source (`private_gems.org`). Right now 0.1 is locked but 0.2 is also available.

When you define the source for `private_gem`:

```ruby
source 'https://rubygems.org'

gem 'public_gem'
gem 'private_gem', '~> 0.1', source: 'https://private_gems.org'
```

and you run `bundle install` it will update `private_gem` to 0.2.

If you would then revert the 0.1 -> 0.2 change from `Gemfile.lock` in order to lock 0.1 again and you run `bundle install` again it will not update `private_gem`.

I hope this is clear enough to be able to reproduce it. :)

**Comment by indirect** [comment]
Thanks for the report! Unfortunately, this isn't something we are able to fix. When gems are listed without a specific source, we have no idea what source they were installed from. As a result, setting a source for a gem absolutely _must_ re-install it from that source, because the existing gem could have come from any source. When installing a gem from a given source, we will apply the usual rules of installing the newest version available from that source that meets the requirements listed in the Gemfile. Once the gem is recorded in the Gemfile and lock file as having been installed from the private source, it is no longer automatically re-installed and updated.

As always, if you care about which version of a gem you get, you _must_ explicitly say so in the Gemfile. If you care about keeping version 0.1, you need to set the version string to '0.1', rather than '~> 0.1'.

**Comment by jeroenj** [comment]
Okay, that's what I already suspected.

In our case it was one of the dependency's dependencies that got a change that breaks our code. This we can obviously solve by restricting the dependency in our Gemflie, but that's how I noticed the other bug from the beginning. :)
