### ISSUE TITLE
How to properly use bundle.config local ?

### ISSUE THREAD

**Issue by rusikf** [bundler/bundler#3645]
After reading [official guide](http://bundler.io/v1.7/man/bundle-config.1.html), i have in Gemfile in project source
```ruby
gem 'fly_admin'
```
1) Run in project source
bundle config local.fly_admin ~/erosite/vendor/engines/fly_admin
2) Check , that option is set :
```
$ bundle config
```
Settings are listed in order of priority. The top value will be used.
local.fly_admin
Set for the current user (/Users/ruslan/.bundle/config): "/Users/ruslan/erosite/vendor/engines/fly_admin"

3) Add in my gem ( i have a rails engine, so add ```raise '123'``` in root controller )
4 )On the project source i run
```
bundle install
```
```
...
Using fly_admin 0.0.3
...
```
5) 
```
bundle update fly_admin
```
```
...
Using fly_admin 0.0.3
...
```

6) The git repo is not changed. Stop rails s and run it again
The raise is not raised. The gem is not updated

Ok,  i can use ```path``` option in gemfile, but i want to use bundle config local without specifing git repository in Gemfile, is it possible ?

**Comment by indirect** [comment]
You cannot use the locals option with `path` gems. You can only use git locals with `git` gems. For more information, please read the documentation on [git locals](http://bundler.io/v1.9/git.html#local).

**Comment by coezbek** [comment]
@indirect What @rusikf is trying to achieve is having the Gemfile reference an officially released Gem (for production) but use a locally copied version for development. Is that possible in any way?

**Comment by indirect** [comment]
@coezbek you can only do that using git gems, so that the lock file can record the git sha used in development and ensure the same sha is used in production. if you don’t care whether the versions match between dev and prod, you don’t need bundler to manage the gem for you. 🙂

**Comment by coezbek** [comment]
That sounds it seem like it is not a legitimate use case. Let me explain better:

- You are working on a project and notice a bug in a Gem. As a good citizen you want to fix this.
- You clone the Gem's repo, check it out, fix the bug.
- Now you want to test the fix before committing/starting the pull request. This is really just temporary. You want avoid any chance that this could end up in production.

What do you do? 
- Local modification of Gem file => Bad because it could be committed by accident.
- Select a different Gem version for environment development => prohibited by Bundler (`You cannot specify the same gem twice coming from different sources.`)
- Use `bundle config local` (this ticket) => Only allowed if both references are `:git`

So what to do?

**Comment by indirect** [comment]
@coezbek in that case, I would modify the Gemfile to use :path instead while testing. If the Gemfile is accidentally committed, then CI will fail because `bundle install` will not be able to find the local `:path`, and you will be safe from accidentally pushing a broken commit to production.
