### ISSUE TITLE
Handle Bundler dependencies better

### ISSUE THREAD

**Issue by strzibny** [bundler/bundler#3647]
Hi,

with new Bundler releases, thor and molinillo dependencies are handled differently (see https://github.com/bundler/bundler/pull/3493/files) than http-net-persistent. Why aren't all bundled dependencies handled the same way? It's already quite tough to unbundle these gems, but now we need to do it differently for different dependencies.

I see from https://github.com/bundler/bundler/issues/3492 that autoload didn't work or? Can you please clarify and make it consistent again? Thanks.

**Comment by segiddins** [comment]
@strzibny can you elaborate why Bundler's current vending strategy isn't working for you?

**Comment by strzibny** [comment]
Look at our specfile which might say more than words:
http://pkgs.fedoraproject.org/cgit/rubygem-bundler.git/tree/rubygem-bundler.spec

Now we would need to do two types of symlinks:
- symlinking thor and molinillo to Bundler's lib (which is on the LOAD_PATH)
- keep symlinking http-net-persistent to /vendor (which adds /vendor path on LOAD_PATH)

I am not saying it's not possible, just weird, ugly and inconsistent.

So my question is, why the offending commit (https://github.com/bundler/bundler/commit/aef35ac138168738323b0f90a2b2d5cd9cf9a379) did not change http-net-persistent bundling as well?

**Comment by segiddins** [comment]
I don't see why you'd need to vendor `thor` and `molinillo` separately from bundler, since bundler takes care to properly namespace those dependencies. As for `http-net-persistent`, as far as I can tell, bundler will only load it if no other version has been previously loaded?

**Comment by strzibny** [comment]
@segiddins This is a Fedora policy[0] that is in place due to the security concerns.

[0] https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

**Comment by segiddins** [comment]
Well, Bundler needs to vendor libraries since it cannot have gem dependencies (due to it itself being a dependency manager). Both Thor and Molinillo are maintained by Bundler contributors, and Bundler is only guaranteed to work with the versions of Thor, Molinillo, and NetHTTPPersistent that it vendors. Additionally, I believe bundler's only official installation method is as a RubyGem.

**Comment by indirect** [comment]
Bundler is not intended to be used as a Fedora package, and in fact the versions of Thor and Molinillo included in Bundler define completely different constants in the Ruby namespace than the public versions of those libraries. This _must_ be done to prevent version incompatibilities between eg the Thor used by Rails and the Thor used by Bundler. You're breaking Bundler by un-vendoring those gems, even if you haven't noticed that it's broken yet.

**Comment by voxik** [comment]
@indirect @segiddins could you please get back to the topic? I.e. make the bundling consistent?

**Comment by segiddins** [comment]
I've yet to really understand what the actual _issue_ is here -- bundler's current vendoring strategies have cause 0 zero issues as far as we know.

**Comment by voxik** [comment]
So what is the answer to this question please:

> With new Bundler releases, thor and molinillo dependencies are handled differently than http-net-persistent. Why aren't all bundled dependencies handled the same way?

**Comment by segiddins** [comment]
The answer is: because thor and molinillo have recently been updated, so I wrote a new vendoring task for them. I've had no reason to do the same for `http-net-persistent`.

**Comment by indirect** [comment]
> Why aren't all bundled dependencies handled the same way?

Because net-http-persistent (not http-net-persistent) has a much more stable API, so we have not yet had to vendor it as carefully yet. Thor and Molinillo both break completely (under some circumstances) if they are required as regular gems.

**Comment by voxik** [comment]
So isn't net-http-persistent worth of the change?

**Comment by indirect** [comment]
Sorry, I don't understand what that question means. So far, net-http-persistent works with any version loaded, so there is no possible conflict with an application using it. Thor (and Molinillo) only work with very, very specific versions, and so they will break other applications that need different versions.

**Comment by indirect** [comment]
Thank you for opening this issue, it gives us the opportunity to make a few things clear about Bundler:

1. Bundler is meant to be installed as a gem.
2. The Bundler team does not provide support for installing or using Bundler as an OS package.
3. The way Ruby handles dependencies unfortunately force us to modify and vendor Thor and Molinillo.
4. The public versions of Thor and Molinillo are not usable by Bundler. Trying to use them instead of the vendored versions will create certain situations where applications are completely broken and unable to function. Please don't do that.

We're not going to change how we vendor things to make it easier to remove vendored code, because removing the vendored code will break both Bundler and applications that use Bundler.

Please stop breaking our library and re-introducing bugs that we have fixed with great effort. Thanks.

**Comment by voxik** [comment]
> Please stop breaking our library and re-introducing bugs that we have fixed with great effort. Thanks.

We are making great effort to not break bundler or any other package. Not sure what would be reason for opposite. And it is interesting to hear that you blaming us for breaking Bundler without any evidence.

I would very much welcome if you could be more open towards packaging, since it si very well possible that at the end, more people are using packaged version of Bundler then its RubyGems version.

Nevertheless, this is cosmetic issue. I am pretty sure you'll fix it one day in the future ....

**Comment by indirect** [comment]
@voxik to pick just one example, using the public Thor as a dependency of Bundler breaks Rails when the version of Thor needed by Bundler and the version of Thor needed by Rails are different.

I'm not talking about a hypothetical bug, I'm talking about actual broken installations of Bundler and Rails that we fixed by changing the Thor inside Bundler. You are undoing our fixes and re-breaking those applications. Please stop.

As for download numbers, I would love to compare. How many times has Bundler been installed as a fedora package? As a gem, Bundler has been installed 41,300,000 times.

**Comment by voxik** [comment]
> I'm not talking about a hypothetical bug, I'm talking about actual broken installations of Bundler and Rails that we fixed by changing the Thor inside Bundler.

Could you be please specific in such cases? What are those versions you are speaking about, what are the specific fixes? So we can check it.

> As a gem, Bundler has been installed 41,300,000 times.

Unfortunately, I don't have any number at my hand. Will try to find some later.

**Comment by indirect** [comment]
@voxik I have already been extremely specific: If you remove Thor from Bundler, then Bundler and Rails may need need to load different versions of Thor.

The `thor` gem creates the Ruby constant `Thor`. The code included in Bundler creates the Ruby constant `Bundler::Thor`. This means they are completely different libraries, and do not conflict with one another. Removing the code included in Bundler re-creates the conflict.

If you need more explanation to understand why that is a problem, please contact me privately, but this ticket has already gone on too long and too far off topic. I'm going to lock it now.
