### ISSUE TITLE
bundler not recognizing the rvm ruby

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [bundler/bundler#3757]
I have the following 3 gems installed related to capistrano:

  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'

In deploy.rb, I specified which ruby I want:

set :rvm_type, :system
set :rvm_ruby_version, 'ruby-2.1.2@core'

I notice that capistrano is running the following command when I deploy to staging:

INFO [040fa832] Running /usr/local/rvm/bin/rvm ruby-2.1.2@core do bundle install --path /var/www/mysite_staging/shared/bundle --without development test --deployment --quiet

It appears that capistrano is ignoring my request to use the core gemset installed at rvm's gemdir. Instead, it is letting bundler manage gems at /shared/bundle. 

I'm ok with that. If bundler wants to mange gems in staging and production, I'm ok with that. The problem is when I go to /shared/bundle/ruby, it has installed the gems in ruby 2.1.0, not 2.1.2, which I specified.

 How can I get bundler to recognize ruby 2.1.2?

**Comment by TimMoore** [comment]
Do you mean that the gems are installed in a directory named `/var/www/mysite_staging/shared/bundle/ruby/2.1.0`? This is normal... that version is the binary compatibility version, and all 2.1.x versions of Ruby use 2.1.0, because binary compatibility is maintained across patch versions.

Is something actually not working for you? If you think there's a bug in Bundler, please follow the steps in https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems for providing details we need to diagnose the problem.

**Comment by TimMoore** [comment]
You can verify the version of Ruby that is used by running `bundle exec ruby -v`.
