### ISSUE TITLE
Bundler relative path symlink

### ISSUE THREAD

**Issue by beedub** [bundler/bundler#3947]
I have a `Gemfile` with `gem 'mygem', path: "../mygem"`. The directory in which `Gemfile` lives is a symlinked directory (eg. `/var/deploy/myapp/current`), which symlinks to `/var/deploy/myapp/releases/20150416/projects/myproject`). I expected `../mygem` to resolve relative to `/var/deploy/myapp/releases/20150416/projects/myproject`), but it resolves with `/var/deploy/myapp/current`, a path that doesn't exist. The results in an error when bundler tries to resolve the paths.

The line in question is https://github.com/bundler/bundler/blob/master/lib/bundler/source/path.rb#L114. It expands the relative path with `Bundler.root`. I'm wondering if that could be changed to `Dir.pwd` instead (or using no argument to `expand_path`; it's the same). Is there some reason why `Bundler.root` is there explicitly?

**Comment by indirect** [comment]
Hi, and thanks for reporting this! Unfortunately, there's no good way to know when it makes sense to expand relative to `Dir.pwd` instead of `Bundler.root`. Because the `bundle` command can be executed with any working directory, including deep inside a bundled application, or even from outside the bundled application directory with the `BUNDLE_GEMFILE` environment variable set, we expand from `Bundler.root`, since it guarantees that relative paths will always resolve the same way.

I would suggest either switching to a `git` gem and using the git locals feature when doing local development, or having capistrano create symlinks inside your releases directory that can be found relative to the actual directory rather than relative to the symlink.
