### ISSUE TITLE
Bundler loading the wrong gem

### ISSUE THREAD

**Issue by hexedpackets** [bundler/bundler#3950]
Using bundler, I'm unable to load the aws-sdk and aws-sdk-v1 gems side-by-side. These gems use different namespaces ("Aws" and "AWS" respectively), and manually loading them works fine. With bundler, the v1 gem is incorrectly loaded when "aws-sdk" is required.

Minimal Gemfile:
```ruby
source 'https://rubygems.org'
gem 'aws-sdk', '~> 2.1.14'
gem 'aws-sdk-v1', '~> 1.52.0'
```

Without bundler:
```
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> Aws
=> Aws
irb(main):003:0> 
```

With bundler:
```
irb(main):001:0> require 'bundler/setup'
=> true
irb(main):002:0> require 'aws-sdk'
=> true
irb(main):003:0> Aws
NameError: uninitialized constant Aws
        from (irb):3
        from /Users/hexedpackets/.rbenv/versions/1.9.3-p551/bin/irb:12:in `<main>'
irb(main):004:0> AWS
=> AWS
```

Bundle env:
```
Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.4.0]
    Git       2.5.0

Gemfile

    source 'https://rubygems.org'
    gem 'aws-sdk', '~> 2.1.14'
    gem 'aws-sdk-v1', '~> 1.52.0'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        aws-sdk (2.1.14)
          aws-sdk-resources (= 2.1.14)
        aws-sdk-core (2.1.14)
          jmespath (~> 1.0)
        aws-sdk-resources (2.1.14)
          aws-sdk-core (= 2.1.14)
        aws-sdk-v1 (1.52.0)
          json (~> 1.4)
          nokogiri (>= 1.4.4)
        jmespath (1.0.2)
          multi_json (~> 1.0)
        json (1.8.3)
        mini_portile (0.6.2)
        multi_json (1.11.2)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)

    PLATFORMS
      ruby

    DEPENDENCIES
      aws-sdk (~> 2.1.14)
      aws-sdk-v1 (~> 1.52.0)

    BUNDLED WITH
       1.10.6
```

**Comment by segiddins** [comment]
Since https://github.com/aws/aws-sdk-ruby/tree/aws-sdk-v1/lib has an `aws-sdk` file, bundler requiring it is totally correct, sadly.

**Comment by indirect** [comment]
Just to expand on that a little: Bundler will automatically require "aws-sdk" or "aws/sdk". Since the v1 gem contains a file whose name conflicts with the other gem, whichever one is earlier in the load path will be required. You _might_ be able to fix it by swapping the order of the gems in your gemfile, but that's not guaranteed. Ultimately, you may need to add the option "require: nil" in your gemfile to stop Bundler from requiring anything, and then manually find the file you actually want and require it specifically in your own code.
