### ISSUE TITLE
Psych is double-loaded unless it's in the Gemfile (redux)

### ISSUE THREAD

**Issue by petergoldstein** [bundler/bundler#4149]
With the latest bundler (1.11.0) and rubygems (2.5.1) on MRI Ruby 2.2.3 I'm seeing the reappearance of the issues noted in #2068 and #2269 .  I'm able to reproduce exactly the set of steps @tenderlove demonstrates in his description of #2068, with the only difference being that my Psych version is 2.0.16.

Rolling back bundler to 1.10.6 or adding Psych explicitly to my Gemfile fixes the issue.  So this looks like the exact same issue as occurred before.

**Comment by indirect** [comment]
Thanks for reporting this! I just fixed it, and added a test that will hopefully keep it from ever cropping up again.

**Comment by EmilienM** [comment]
@indirect could we have a release including this change as soon as possible?

**Comment by segiddins** [comment]
@EmilienM asking for releases doesn't speed up the release schedule. We'll put out a new bug fix release when we're able to. In the meantime, 1.10.6 works just fine.

**Comment by EmilienM** [comment]
@segiddins I'm asking because this release is broken and a lot of downstream CIs are broken too. I'm working on OpenStack project and we run a CI that always uses the latest bundler release. The latest is broken so we have to pin a previous one (which is weird to me, isn't?).
So I think you should provide a release soon if you want to keep your users happy.

**Comment by segiddins** [comment]
@EmilienM I work on bundler in my spare time. I took time out of my vacation to do this release, which followed two weeks of prereleases in which we received literally 0 error reports. Making demands discourages me from putting more of my free time into bundler, and certainly won't make a release happen sooner.

**Comment by EmilienM** [comment]
@segiddins Making demands is actually free feedback from your users of the project in which you're spending your free time on; that's something valuable for you and you might want to take it in account.
I'm sorry if you're took time during your vacations, that's something I can't really help with. But I'm raising here something that a ton of users are facing now, with this new (broken) release.

Our CI is now pinned and we use an old like you suggested. Which means we won't give feedback on future Bundler patches, since we can't test them. That's also bad for you, and that's why a new release with allow people to continue to stay on the edge of Bundler.

Good luck!

**Comment by jrafanie** [comment]
@EmilienM is it easy for you to add `--pre` to your CI so you can install pre-release bundlers and help report these issues earlier?  http://guides.rubygems.org/patterns/#prerelease-gems

**Comment by EmilienM** [comment]
@jrafanie to make OpenStack CI unstable? No, thank you. That's definitely not Puppet OpenStack modules mission statement. I would rather try to figure how this patch could have been merged in bundler and pass Travis CI.

**Comment by chrisarcand** [comment]
@EmilienM I think @jrafanie was referring to the future general case, not just this particular issue :) Certainly not a good thing to do at this very moment. Understandable if it can't be done regardless, though.

**Comment by indirect** [comment]
@EmilienM There wasn't a test that covered the specific case of requiring psych after setting up a Gemfile that didn't include psych. There is a test now.

Your demands that we do free work for you whenever is most convenient for you are quite rude. The only way we could have discovered and fixed this sooner is if you used prereleases, which you also just refused to do.

We'll release as soon as we can, no matter what your demands are, but this is your single warning for violating the code of conduct. Be respectful of our donated time and work, instead of demanding more of it, if you want to post here.

**Comment by EmilienM** [comment]
@indirect I'm not sure I violated any code of conduct. This is an Open-Source project, you might want to hear from your users (happy or not).
Because this project is managed by people working on their free time is not a good reason to forbid people to give thoughts and asking for a release when it's really relevant (like here, latest release is just broken).

Again, we pinned our CI so we don't have the bug anymore. The release request was more for the whole Bundler users community, who is now installing a broken version by default.

"Be respectful of our donated time and work": I'm very respectful again, by giving you feedback on the project you're leading. I also know what does it mean to give time on Open-Source, I'm contributing to several Open-Source projects; that's also my full-time position.

Anyway, I'm not sure this conversation is going somewhere; it's clear a release is not going to happen soon, which is a good information for Bundler's users.

Thank you for your work (on spare time or not) and for listening the feedback, that I think what really matters for people who use Bundler.

**Comment by indirect** [comment]
@EmilienM since this is apparently a surprise to you: you don't get to decide whether you violated the code of conduct or not. By the same token, you don't get to decide whether you're being respectful or not.

It's not okay to say "you should provide a release soon if you want to keep your users happy", because that means you are telling us what to do (not cool), telling us when to do it (also not cool), and telling us that you speak for all users of Bundler (which is false, as well as not cool).

If you'd like to ask for a release in the future, say something like "Thanks for fixing this! Do you know when you'll be able to release the fix?". That makes it clear that you appreciate our work, and also makes it clear that you don't think we owe you our free work.

I'm aiming to push the 1.11.1 release, including the fix for this bug, by the end of the day today.

**Comment by EmilienM** [comment]
@indirect Please explain me what in the code of Conduct (https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md) I did wrong, specially from harassment list:
"offensive verbal comments related to level of experience, gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, ethnicity, age, religion, nationality, the use of sexualized language or imagery, deliberate intimidation, stalking, sustained disruption, and unwelcome sexual attention".

This conversation is going very far, I just asked for a release, which is something very common in many projects. If it's not common to let your users do requests, I would be happy to add that to your code of conduct.

For 1.11.1, thank you for this work, it will be very helpful for the users.

**Comment by indirect** [comment]
@EmilienM I just explained exactly what was problematic about what you said, and exactly how to ask without being demanding or rude. You ignored my explanation and tried to say again that we "refuse requests from users". We're done here.

**Comment by agis-** [comment]
Closing as this is fixed by #12796.
