### ISSUE TITLE
Installing beef on Windows 10

### ISSUE THREAD

**Issue by strathaxxs** [bundler/bundler#4176]
-
- What did you do?

  I ran the command `C:/Ruby22/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install beef.

- What happened instead?

  Instead, what actually happened was it showed this message:

Error details
```
    SyntaxError: C:/Ruby22/lib/ruby/site_ruby/devkit.rb:13: syntax error, unexpe
cted '<', expecting end-of-input
<% tool_names.each_pair do |k,v| -%>
 ^
      C:/Ruby22/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:3:in `load'

      C:/Ruby22/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:3:in `block
 in <top (required)>'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:275:in `call'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:275:in `block in run_pre_in
stall_hooks'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:274:in `each'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:274:in `run_pre_install_hoo
ks'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:235:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/rubyg
ems.rb:142:in `block in install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/rubygems_int
egration.rb:151:in `preserve_paths'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/rubyg
ems.rb:134:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/ge
m_installer.rb:56:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/ge
m_installer.rb:14:in `install_from_spec'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/pa
rallel_installer.rb:90:in `block in worker_pool'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55
:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55
:in `apply_func'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:50
:in `block in process_queue'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47
:in `loop'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47
:in `process_queue'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:22
:in `block (2 levels) in initialize'
```
Environment
```
    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
    GEM_HOME  C:/Ruby22/lib/ruby/gems/2.2.0
    GEM_PATH  C:/Ruby22/lib/ruby/gems/2.2.0;C:/Users/****/.gem/ruby/2.2.0
    Git       not installed
```

**Comment by rgb-one** [comment]
It is recommended that you install ruby version `2.1.X` on the [RubyInstaller][] website because it is stable and provides a wider range of supported packages; maybe you could give that a try as well as install the corresponding DevKit for that version of Ruby. 

There may be an issue with the version of DevKit you have installed. You can lodge a bug report to [RubyInstaller issue tracker][]. Make it more clear than the issue you lodges here ;).

I will ask some questions to that you can answer that may help you troubleshoot.
1. The Ruby you have installed is version 2.2.3 and is for the i386 architecture. Does the DevKit you have installed match that version and architecture of the installed Ruby?
2. Have you followed all the steps to [install DevKit][] correctly?

Also, install git. You will need it when dealing with gems from git repositories.

This isn't bundler related so I am gonna close this.

[RubyInstaller]:http://rubyinstaller.org/downloads/
[steps to install DevKit]:https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#building-the-devkit
[RubyInstaller issue tracker]:https://github.com/oneclick/rubyinstaller/issues

**Comment by TimMoore** [comment]
No response: closing
