### ISSUE TITLE
Notify of major version updates on `bundle update`

### ISSUE THREAD

**Issue by tejasbubane** [bundler/bundler#4313]
On similar lines of #4243 

Currently `bundler` silently updates the gems even if it is a major update. 
eg.

```
⇒  bundle update
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using diff-lcs 1.2.5
Installing rspec-support 3.4.1
Using bundler 1.11.2
Installing rspec-core 3.4.3 (was 2.14.8)
Installing rspec-expectations 3.4.0 (was 2.14.5)
Installing rspec-mocks 3.4.1 (was 2.14.6)
Installing rspec 3.4.0 (was 2.14.0)
Bundle updated!
⇒  bundler -v
Bundler version 1.11.2
```

This might happen when you update old applications with no version numbers specified in `Gemfile`.
eg.

```
gem 'rspec'
```

I think it would be nice to notify users how many gems were updated in total and how many of them were major version upgrades (like `rspec` and its dependencies in the above example).
If possible we should also ask users to look at the changelog for that major release since it would have breaking changes.

I can work on this. Let me know what you people think.

**Comment by seanlinsley** [comment]
I'd be all for this, except it would make the already long output even longer. I'd like to see a more succinct output, perhaps by only printing gems that were newly installed, or were upgraded. For all other gems we could use `\r` to reuse the latest line of output in the terminal to show progress ([example](http://stackoverflow.com/a/4963752)). If the verbose version is needed for debugging, we could write it to a log file.

Unfortunately both of our proposals would require a major version bump, since as I understand it people write tools that parse the output.

**Comment by seanlinsley** [comment]
It seems that this ticket should have been created on the bundler-issues project: https://github.com/bundler/bundler-features

**Comment by tejasbubane** [comment]
@seanlinsley Oh, I did not know that a features repo exists.

**Comment by segiddins** [comment]
Yup, belongs on the features repo :+1:
