### ISSUE TITLE
Bug in default gemspec spec.executables

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4544]
_From @stephan-nordnes-eriksen on June 27, 2014 13:23_

I recently experienced a bug with the default spec.executables in the gemspec generated after "bundle gem new_gem".

I added a folder into a /bin folder, and that caused the command to remove sub-folders in the path of the executables.

```
spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
```

Example:
If you have a file stored like this:

```
bin/sub_binary_folder/some_executable.extension
```

It will be added as:

```
bin/some_executable.extension
```

And thus the gem won't build.

To fix this, I made the following change:

```
spec.executables   = spec.files.grep(%r{^bin/}) { |f| f[3..-1] }
```

It is a bit crude, but it essentially strips away the extra "bin/" which is prepended to the path.

_Copied from original issue: bundler/bundler-features#57_

**Comment by LynnCo** [comment]
_From @indirect on June 27, 2014 16:41_

I'm not totally convinced this is a bug. Folders in bin doesn't really make sense for a gem, because Rubygems and Bundler will create files in a bin directory for each of the gem bins. it would be equally weird to have a subdirectory in /usr/bin; your PATH wouldn't make sense anymore.


Why do you want to create folders in bin? What's the problem you are trying to solve?

**Comment by LynnCo** [comment]
_From @stephan-nordnes-eriksen on June 27, 2014 21:56_

I have thought a bit about this, and to me it seems like an artificially enforced best practice. Yes, it might be best practice to have a flat structure in the bin-folder, but I don't really see any good reason for why you shouldn't be allowed to make a folder structure if you wanted to. You might have a bunch of related binaries in one folder for instance.

In my case I ran into this issue sort of unwillingly because I simply copied a bin-folder from a completely different project which I needed. It had a more complex structure and included some non-executable files. I could possibly have put it somewhere else, but the bin-folder was the most natural one.

Anyways. I do think it is an issue that could be addressed. If the decision is to have a flat structure it would be beneficial to inform about this somewhere, somehow, so that others like me would not run into these strange errors.

**Comment by LynnCo** [comment]
_From @indirect on June 28, 2014 4:23_

I'm not quite sure I buy that. The actual Ruby code that is run by your gem is explicitly agreed to be in `lib`. Putting a directory in `bin` means that Rubygems will either ignore it entirely (which I think is the case) or it will try to create an entire directory somewhere in your PATH. The entire point of the gem `bin` is so that Rubygems knows what to put into the directory on your PATH. Unix paths aren't designed to work with subdirectories, so it's very strange to me that you want to put directories into your `bin`.

**Comment by segiddins** [comment]
@indirect what do you think we should do about this? Close as a wontfix?

**Comment by colby-swandale** [comment]
ping @indirect

**Comment by indirect** [comment]
@colby-swandale thanks <3

@segiddins I think we can probably close this. If you put directories in `bin`, it's up to you to change the gemspec to exclude the directory from the list of executables.
