### ISSUE TITLE
Add simple 'read_gemfile' API

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4551]
_From @bitops on September 18, 2013 22:31_

It would be quite convenient if Bundler exposed a simple API like Bundler.read_gemfile(path_to_gemfile) which took the path to a Gemfile, analyzed its dependencies, and returned a list of Gem specifications, similar to Bundler.setup. This API should just work without having to mess with environments or any such thing.

_Copied from original issue: bundler/bundler-features#25_

**Comment by LynnCo** [comment]
_From @segiddins on March 8, 2015 0:25_

This is already what a `Bundler::Definition` does under the hood...

**Comment by segiddins** [comment]
I'm happy to close this as something a plugin should do

**Comment by LynnCo** [comment]
@segiddins do we have a list of desired plugins somewhere? Also do we explicitly require more code changes past 1.12 to allow people to create plugins?

**Comment by segiddins** [comment]
you can already `require 'bundler'` so no, explicit changes are not required for this type of plugin. And I don't think these are really _desired_ plugins per se, but more the sort of thing our users might want to make as plugins since it's functionality not core to bundler itself that we don't want to have to maintain

**Comment by LynnCo** [comment]
Gotcha, so the original creator can implement this feature on their own if they so desire, which means no changes are required on our part. Closing -
