### ISSUE TITLE
Add subcommands to `config`

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4600]
Today, it's confusing that `config` lets you pass the flags `local`, `global`, and `delete` in any combination.
It would be an improvement to the interface of `config` if Bundler 2 supported a slightly different set of commands, e.g.:

```
# Setting
$ bundle config set foo bar
# Unsetting
$ bundle config unset foo bar
# Local-only
$ bundle config set foo bar --local
# Global-only
$ bundle config set foo bar --global
```

**Comment by denniss** [comment]
@indirect may I give this one a shot?

**Comment by indirect** [comment]
yes, definitely! sounds awesome :)

**Comment by indirect** [comment]
I think starting an implementation is a good way to figure out if there are issues that we need to discuss. :)

**Comment by denniss** [comment]
@indirect I am using existing `config_spec` to test my implementation of this feature. While looking through the existing specs, I found this one to be somewhat confusing: https://github.com/bundler/bundler/blob/master/spec/commands/config_spec.rb#L217

Specifically, shouldn't the line:
```
run "puts Bundler.settings.send(:global_config_file).read"
```
be 

```
run "puts Bundler.settings.send(:local_config_file).read"
```

Since the previous command is calling `bundle config foo '1'`.

**Comment by indirect** [comment]
@denniss yup, that looks like a mistake. No idea how it's passing. 😮

**Comment by denniss** [comment]
I think that actually might be the expected behavior. Although, I find it kind of confusing. From `bundle help config`

>  Executing bundle config <name> <value> will set that configuration to the value specified for all bundles executed as the current user. The configuration will be stored in ~/.bundle/config. If name already is set, name will be overridden and user will be warned.

I'd like to propose a couple change to the behavior of the config command. 
- I feel like global configuration should only be changed when `--global` is specified. 
- Setting a value where there are spaces involve should require quotes. 
E.g. 
`bundle set config build.mysql --with-mysql-config=/usr/local/mysql/bin/mysql_config`
Should be
`bundle set config build.mysql '--with-mysql-config=/usr/local/mysql/bin/mysql_config'`

May be @segiddins can chime in on this?

**Comment by segiddins** [comment]
Those are both breaking changes, which we wouldn't be able to ship in Bundler 1.x

**Comment by indirect** [comment]
@segiddins yes, this entire PR is already in 2.0 territory. But I'm comfortable with starting work on that now, I think.

**Comment by indirect** [comment]
@denniss I like both of those changes, I think 👍

**Comment by segiddins** [comment]
In that case, I love the idea :)
