### ISSUE TITLE
`bundle outdated` with gem on multiple platforms will not show updates for both platforms

### ISSUE THREAD

**Issue by RochesterinNYC** [bundler/bundler#4664]
- Related to #4450 and https://github.com/bundler/bundler/pull/4465#issuecomment-214135134

Reiteration of problem:
In the case of a gem `laduradura` being used for both ruby and java platforms, with an update available for the gem on java platform, `bundle outdated` will not show any potential updates. However, it will show an update available if the update is available on the ruby platform.

Failing spec:

```
diff --git a/spec/commands/outdated_spec.rb b/spec/commands/outdated_spec.rb
index 6420c28..57d9d64 100644
--- a/spec/commands/outdated_spec.rb
+++ b/spec/commands/outdated_spec.rb
@@ -257,6 +257,21 @@ describe "bundle outdated" do
     end
   end

+  context "update available for a gem on the same platform while multiple platforms used for gem" do
+    before do
+      install_gemfile <<-G
+        source "file://#{gem_repo2}"
+        gem "laduradura", '= 5.15.2', :platforms => [:ruby, :jruby]
+      G
+    end
+
+    it "reports that updates are available" do
+      bundle "outdated"
+      expect(out).to include("Outdated gems included in the bundle:")
+      expect(out).to include("laduradura (newest 5.15.3, installed 5.15.2, requested = 5.15.2)")
+    end
+  end
+
   shared_examples_for "version update is detected" do
     it "reports that a gem has a newer version" do
       subject
```

**Comment by b-ggs** [comment]
I'll work on this.

**Comment by b-ggs** [comment]
Quick question about the spec:

For context:
```
[1] pry(#<Bundler::CLI::Outdated>)> whereami

Frame number: 0/11

From: /home/boggs/dev/bundler/lib/bundler/cli/outdated.rb @ line 59 Bundler::CLI::Outdated#run:

    54:           active_spec = definition.specs.detect {|spec| spec.name == current_spec.name && spec.platform == current_spec.platform }
    55:         else
    56:           active_specs = definition.index[current_spec.name].sort_by(&:version)
    57:           binding.pry
    58:           # active_specs = definition.index[current_spec.name].select {|spec| spec.platform == current_spec.platform }.sort_by(&:version)
 => 59:           if !current_spec.version.prerelease? && !options[:pre] && active_specs.size > 1
    60:             active_spec = active_specs.delete_if {|b| b.respond_to?(:version) && b.version.prerelease? }
    61:           end
    62:           active_spec = active_specs.last
    63:
    64:           if options[:major] || options[:minor] || options[:patch]
```

So I'm checking out how `bundle outdated` determines whether there are updates, and it seems that it only picks up that `ruby` is the only platform specified in the Gemfile.
```
[1] pry(#<Bundler::CLI::Outdated>)> gemfile_specs.map(&:name)
=> ["laduradura"]
[2] pry(#<Bundler::CLI::Outdated>)> gemfile_specs.map(&:version)
=> [Gem::Version.new("5.15.2")]
[3] pry(#<Bundler::CLI::Outdated>)> gemfile_specs.map(&:platform)
=> ["ruby"]
```

Despite the fact that `dependency` lists both `ruby` and `jruby as the platforms.
```
[4] pry(#<Bundler::CLI::Outdated>)> dependency
=> Gem::Dependency.new("laduradura", Gem::Requirement.new(["= 5.15.2"]), :runtime)
[5] pry(#<Bundler::CLI::Outdated>)> dependency.platforms
=> [:ruby, :jruby]
```

If I remove `ruby` from the Gemfile and just put the following in:
```
gem "laduradura", '= 5.15.2', :platforms => [:jruby]
```

`bundle outdated` seems to skip over `laduradura` as a whole.
```
[1] pry(#<Bundler::CLI::Outdated>)> gemfile_specs
=> []
```

Still looking into why it does that, but while checking, I came across another peculiarity.

For context, a small snippet from the `whereami` dump above.
```
    56:           active_specs = definition.index[current_spec.name].sort_by(&:version)
    57:           binding.pry
    58:           # active_specs = definition.index[current_spec.name].select {|spec| spec.platform == current_spec.platform }.sort_by(&:version)
```

I removed the `select` method that excludes out the gems on different platforms, and found that the platform specified in the update is `java` and not `jruby`.
```
[1] pry(#<Bundler::CLI::Outdated>)> active_specs.map(&:version)
=> [Gem::Version.new("5.15.2"), Gem::Version.new("5.15.2"), Gem::Version.new("5.15.3")]
[2] pry(#<Bundler::CLI::Outdated>)> active_specs.map(&:platform)
=> ["ruby", "java", "java"]
```

So, I tried swapping out `jruby` for `java` in the Gemfile. Which resulted in the following:
```
$ cat Gemfile 
source "file:///home/boggs/dev/4664-bundle-outdated-test/gems/remote2"
gem "laduradura", '= 5.15.2', :platforms => [:ruby, :java]
$ dbundle install
[!] There was an error parsing `Gemfile`: `java` is not a valid platform. [...]
```

If `java` isn't a valid platform, and `jruby` is, then how is it ever updated via `bundle outdated`?

The original line that checks filters out updates from different platforms is:
```
active_specs = definition.index[current_spec.name].select {|spec| spec.platform == current_spec.platform }.sort_by(&:version)
```

Even if `jruby` is specified in `current_spec.platform`, then it still wouldn't be updated since `java` is the actual platform of the `laduradura` gem.

Can't seem to determine whether the spec is wro

**Comment by b-ggs** [comment]
@RochesterinNYC I've investigated further after having installed JRuby.

```
[5] pry(#<Bundler::CLI::Outdated>)> whereami

From: /home/boggs/dev/bundler/lib/bundler/cli/outdated.rb @ line 58 Bundler::CLI::Outdated#run:

    53:         if options["strict"]
    54:           active_spec = definition.specs.detect {|spec| spec.name == current_spec.name && spec.platform == current_spec.platform }
    55:         else
    56:           # active_specs = definition.index[current_spec.name].sort_by(&:version)
    57:           active_specs = definition.index[current_spec.name].select {|spec|
 => 58:             binding.pry
    59:             spec.platform == current_spec.platform
    60:           }.sort_by(&:version)
    61:           if !current_spec.version.prerelease? && !options[:pre] && active_specs.size > 1
    62:             active_spec = active_specs.delete_if {|b| b.respond_to?(:version) && b.version.prerelease? }
    63:           end
```

At this breakpoint, the `select` method is only picking out the `spec`s whose `spec.platform` matches the `current_spec.platform`.

The issue here lies in the following:
```
[6] pry(#<Bundler::CLI::Outdated>)> spec.name
=> "laduradura"
[7] pry(#<Bundler::CLI::Outdated>)> current_spec.name
=> "laduradura"
[8] pry(#<Bundler::CLI::Outdated>)> spec.platform
=> "java"
[9] pry(#<Bundler::CLI::Outdated>)> current_spec.platform
=> #<Gem::Platform:0x90a @cpu=nil, @os="java", @version=nil>
[10] pry(#<Bundler::CLI::Outdated>)> spec.version
=> Gem::Version.new("5.15.3")
[11] pry(#<Bundler::CLI::Outdated>)> current_spec.version
=> Gem::Version.new("5.15.2")
```

As can be observed here, `spec` which contains the updated version of `laduradura`'s `platform` is `!=` to the `current_spec`'s `platform`.

This is the reason why `laduradura` wasn't reported as outdated, because the `select` method removed the updated version because the `platform`s didn't match.

**Comment by b-ggs** [comment]
@RochesterinNYC One workaround is using `to_s` on the `platform` so the two can be correctly compared against each other.

```
[16] pry(#<Bundler::CLI::Outdated>)> spec.platform
=> "java"
[17] pry(#<Bundler::CLI::Outdated>)> current_spec.platform
=> #<Gem::Platform:0x90a @cpu=nil, @os="java", @version=nil>
[18] pry(#<Bundler::CLI::Outdated>)> current_spec.platform.to_s
=> "java"
```

**Comment by b-ggs** [comment]
@RochesterinNYC Also, I have a question. Wouldn't the spec you gave in the issue description not work at all, since Travis only runs the specs in Ruby? 

One of the ways I can see the spec working is if I remove the entire `select` block that filters out different platforms, but that would break other specs associated with reporting only outdated gems of the same platforms.

**Comment by segiddins** [comment]
@b-ggs use https://github.com/bundler/bundler/blob/58fc66897b156ce91eb98710f7708f8abe36c806/lib/bundler/match_platform.rb#L8

**Comment by RochesterinNYC** [comment]
@b-ggs Let's try the string comparison (only if the types of `current_spec.platform` and `spec.platform` don't match) for a first implementation.

You can simulate running as JRuby (or any other Ruby engine) in the specs with `simulate_ruby_engine`: https://github.com/bundler/bundler/blob/master/spec/support/helpers.rb#L352

Ex. https://github.com/bundler/bundler/blob/master/spec/other/platform_spec.rb#L289

**Comment by b-ggs** [comment]
@segiddins @RochesterinNYC Gotcha. Let me open a PR with an initial solution.

**Comment by mikegee** [comment]
Was this issue resolved by https://github.com/bundler/bundler/pull/5273>

**Comment by segiddins** [comment]
Believe so!
