### ISSUE TITLE
Bundler test suite should run on Appveyor against PRs

### ISSUE THREAD

**Issue by RochesterinNYC** [bundler/bundler#4665]
We're looking to run the Bundler test suite against new/updated Bundler PRs on Windows environments via [Appveyor](https://ci.appveyor.com/project/AndrArko/bundler).
- A work-in-progress PR was made early on at #4299, but I don't currently have the time bandwidth to undertake this work right now.
- Additionally, @indirect, think we should be using an Appveyor account that isn't a personal account (it's currently under your `AndreArko` user?

**Comment by allenzhao** [comment]
Any updates/thoughts on this?
I want to pick up this btw

**Comment by RochesterinNYC** [comment]
Go ahead. @allenzhao

@indirect thoughts on the personal vs. official account thing?

**Comment by allenzhao** [comment]
Note:
https://www.appveyor.com/docs/installed-software#ruby
Documentation says some rubies are already installed but with bundler
Will this affect build process?
And btw, https://github.com/bundler/bundler/pull/4299 might be a starting point for me

**Comment by RochesterinNYC** [comment]
I don't believe that the test suite will use the system Bundler.

**Comment by allenzhao** [comment]
Been working on this for a little while now and three things need to be mentioned:

1.  `rake spec:deps` stops working for some strange reason:
https://github.com/bundler/bundler/blob/master/Rakefile#L58 Setup failed because of a `The system cannot find the file specified.` error. 
Seems related to [Spec::RubyGems.setup](https://github.com/bundler/bundler/blob/master/spec/support/rubygems_ext.rb#L25). Since it's called multiple times afterwards, it is important to make this installable on Windows.
2.  Some dependencies should also be installed, to run the test. (e.g. Graphviz, groff)
3.  https://github.com/bundler/bundler/blob/master/spec/spec_helper.rb#L25 won't be necessary since Open3 already works on ruby 2.2 on Windows (as I'm testing) and AppVeyor's lowest version of Ruby is 1.9.3, so win32-open3 won't be necessary.

**Comment by colby-swandale** [comment]
We've merged #6899 to test Bundler on Windows using Azure pipelines.
