### ISSUE TITLE
Rescue `Java::JavaLang::OutOfMemoryError` and print a useful error message

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4673]
As reported in #4572, it's very possible for Bundler to run the JVM out of memory, especially on memory-constrained JVM instances. We should rescue this error and print an explanatory message, rather than barfing a stacktrace and asking users to report the bug as a new issue. Here's a draft error message:

> Your JVM has run out of memory, and Bundler cannot continue. You can decrease the amount of memory Bundler needs by removing gems from your Gemfile, especially large gems. (Gems can be as large as hundreds of megabytes, and Bundler has to read those files!). Alternatively, you can increase the amount of memory the JVM is able to use by running Bundler with `jruby -J-Xmx1024m -S bundle` (JRuby defaults to 500MB).

**Comment by segiddins** [comment]
Can just add this to friendly_errors

**Comment by headius** [comment]
FWIW, JRuby already will display such a message if the OOM bubbles all the way out, and memory errors can be notoriously tricky to rescue (because we're at a memory limit already). Feel free to add this message if it fits the rest of the system though, and let me know if you have any trouble rescuing the error.
