### ISSUE TITLE
CVE-2016-7954 secondary sources

### ISSUE THREAD

**Issue by wwood** [bundler/bundler#5051]
Hi,

I'm just wondering where the code is at re this vulnerability? Is there a fix?
http://seclists.org/oss-sec/2016/q4/18

Apologies if I missed the answer to this q elsewhere.
Thanks, ben

**Comment by indirect** [comment]
Hi there. No one has contacted the Bundler team in any way regarding this vulnerability yet. We believe that we have already fixed the issue in an upcoming release, but there is no way to tell, since no one has bothered to give us the details of the supposed CVE.

**Comment by sfcgeorge** [comment]
What I could find:

* 2015-05-21 [This issue](https://github.com/bundler/bundler/issues/3671) was reported that appears to be the same thing. Closed; as it's fixed in 2.0 (but not 1.x).
* 2016-04-01 The blog post below suggests the Bundler team was contacted in April by email. No details of the contact. Searching the mailing list for ["secondary source"](https://groups.google.com/forum/#!searchin/ruby-bundler/secondary$20source%7Csort:relevance) and ["CVE-2016-7954"](https://groups.google.com/forum/#!searchin/ruby-bundler/CVE-2016-7954%7Csort:relevance) comes up with nothing.
* 2016-10-04 CVE was [requested](http://seclists.org/oss-sec/2016/q4/18) and ["reserved"](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7954).
* 2016-10-04 [Reed Loden's comment](http://seclists.org/oss-sec/2016/q4/25) says further contact was made with the response that the 2.0 fix can't be backported to 1.x due to lockfile incompatibility.
* **2016-10-06** Steve Richert wrote this [blog post](http://collectiveidea.com/blog/archives/2016/10/06/bundlers-multiple-source-security-vulnerability/) about the CVE which he reported (I saw it on twitter). There are GIFs that appear to show a replication (I realise GIF immediately suggests ✨🐱✨ but it seems convincing).

Could this be a security issue in real world production environments? One thing that springs to mind is [Rails Assets so I've opened a feeler issue there](https://github.com/tenex/rails-assets/issues/379). Of course GitHub and Bitbucket inline sources are common too.

If it could be a real security issue, and assuming a fix can't be backported, should a warning be added suggesting the no top level source using only blocks workaround?

Was the team contacted, what was the actual response? How does [RubyTogether](https://rubytogether.org) fit into this, would additional funds from concerned parties help? Does RubyTogether prioritise security fixes (I don't see it on the site)?

I'm just collating info that may or may not be helpful, not trying to stir alarm or anything. You all do a great job, and it's really appreciated 💟

**Comment by sfcgeorge** [comment]
I've been able to verify this affects git and github remotes too - all gemspecs in that single repo will be considered for all global gems. https://github.com/sfcgeorge/gem_clash

However I'm struggling to think of a real world way this could be exploited. It would be easier for a rogue gem author to add malicious code to their own gem than add a second fake gem for "rails" or whatever.

**Comment by lynnco** [comment]
Here is our plan to address this so far: https://github.com/bundler/bundler/issues/5062

**Comment by colby-swandale** [comment]
This issue has been quiet for a while now and i feel that there is nothing left to add to this specific ticket. I'm going to close it for now.
