### ISSUE TITLE
Stub the real world tests with vcr

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#5099]
The [real world tests](https://github.com/bundler/bundler/tree/master/spec/realworld) make need to make requests against external servers in order to pass. This leads to issues such as the tests breaking when a gem releases a new version, among other things. To circumvent this, the tests can be stubbed with [vcr](https://github.com/vcr/vcr).

See [this PR](https://github.com/how-is/how_is/pull/66/files) for an example vcr implementation

This involves:
- [ ] adding vcr to `bundler.gemspec`
- [ ] setting up vcr in `spec_helper.rb`
- [ ] wrapping the real world tests with vcr
- [ ] adding a script to reload the casettes into `rake release`

**! Important !** I need to completely rewrite the expectations of this feature to address https://github.com/bundler/bundler/issues/5099#issuecomment-254646393. Until then, the above details will be inaccurate

**Comment by chrismo** [comment]
would this be with the idea of re-recording cassettes regularly? or just using the cassettes permanently? If the latter, there's no point in really having 'real' world tests that are faked out?

**Comment by lynnco** [comment]
@chrismo I re-record my cassettes with every minor version

**Comment by chrismo** [comment]
had to deal with too many other teams that use VCR as a mock library ... which is silly :)

**Comment by indirect** [comment]
Unfortunately in our specific tests this is a lot more complicated than it is in the example linked above. :( I would be very happy to have mocked tests that are easy to update, but we'll need to come up with some way to insert VCR into the Bundler subprocess that is run by the tests—loading VCR into RSpec won't do it, because RSpec runs Bundler in a subprocess that will not inherit VCR.

Implementing this will probably mean creating a test support file that loads and sets up VCR, and then creating an option for the `bundler` method that allows enabling VCR and choosing a cassette by name, and then passing that to the subprocess via an environment variable, and then ensuring that the subprocess loads the helper file via `RUBYOPT` so that the helper can require VCR and set up the cassette based on the name given in the env var. Or something like that. :waves hands:
