### ISSUE TITLE
Denied

### ISSUE THREAD

**Issue by danceswithcats** [bundler/bundler#5138]
Sorry, I've no idea what I'm doing, but github said that this was not an existing issue.

https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_file_s_rename+-+%28%2Ftmp%2Fbundler-compact-index-20161030-6591-1e7xk7w%2Fversions%2C+%2Fhome%2Fpeter%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions%29&type=Issues

**Comment by bitboxer** [comment]
Hi @danceswithcats, can you explain your problem you are having right now?

**Comment by lynnco** [comment]
@danceswithcats you have your local path in the search parameter:

> `...home/peter/.bundle...`

The search you actually want is: https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied+%40+rb_file_s_rename&type=Issues

The path thing should have been resolved by https://github.com/bundler/bundler/issues/4771, so I'm not sure why it's still around.

---

Closing this issue since it's about the search, rather than the permissions error itself. Look through that search and make a new issue if needed
