### ISSUE TITLE
Reword the call out message for giving back in PR #5308

### ISSUE THREAD

**Issue by hmistry** [bundler/bundler#5311]
This is in regards to PR #5308.

I really feel the tone of the message is not the best, and after much thought concluded that it's because the message singles out profitable companies/individuals. To me the tone is kind of like "if you're making money, pay up". I'm sure this is not the sentiment of the team, and it's more of an appeal to those who can afford it to help us cover the costs, so let's phrase it that way and leave it open for the individuals to decide if they can afford it.

Here are some alternative messages we can use:
1. Bundler and RubyGems.org are currently free for everyone to use, but maintaining them costs more than $20,000 USD every month. Help us cover those costs so we can keep the gem ecosystem free for everyone: https://rubytogether.org/join

2. We need your help. It costs Ruby Together more than US$20,000 per month to maintain Bundler and RubyGems.org. Help us cover the costs by joining for as little as US$10/month at https://rubytogether.org/join and let's keep the gem ecosystem free for everyone.

3. Bundler and RubyGems.org are currently free for everyone to use, but maintaining them costs more than $20,000 USD every month. Help us cover those costs so we can keep the gem ecosystem free for everyone by joining for as little as US$10, see: https://rubytogether.org/join

4. Please help Ruby Together keep the gem ecosystem free for everyone because it costs more than US$20,000 a month to maintain Bundler and RubyGems.org. You can help for as little as US$10 by joining at https://rubytogether.org/join

Feel free to change it as desired but avoid singling out a group and let's try to keep a friendly "need help" tone. If we can think of a stronger benefit than simply keeping the gem ecosystem free, that would be good. Also, would be good to track the url leads so when we try different messages, we can see conversions.

I appreciate you reconsidering the message, @indirect, @segiddins. 😃

**Comment by indirect** [comment]
@hmistry ahh, I see what you're saying. Far from trying to call out profitable companies, I included that because I often need to ask people to _not_ give money unless they are making money using Ruby. Devs who feel good about Ruby get very concerned and start offering money, even if they are only casual users or are otherwise not making a profit. What we want is for profitable devs and companies to give back to the community, so that devs and companies that are bootstrapping, or teaching, or just doing it for fun, can all use the same tools for free.

My goal with that wording was to clarify that we are not looking for money from casual users, but we are looking for money from those using Ruby to make a profit. Can you update your suggestions to include that point?

**Comment by hmistry** [comment]
@indirect Ok so that makes this more complicated. Here are some quick thoughts:

If you want to reach out to profitable businesses, then I'd say this is the wrong place to do it. A direct email campaign would be a better approach. For a message in bundler, one thought is we have a broader message to evangelize the dev's to talk to their businesses to help us... think of this as lead generation and the landing page on rubytogether.org/join can go in more details.

I wouldn't worry about profitability requirement because I think that's what turns the message negative, and it's automatically taken care of by what people can afford. For the 1 out of 10 that are not profitable and still want to support us, well these people who are serious do-gooders and it makes them happy to do it. Refusing them makes them unhappy and we steer them to some other org's, so let's not close that door because they will be even bigger supporters when they do turn a profit.

I'll think about how we can change the message, and I'll talk to you offline because I have some questions and need to understand your angle better.

**Comment by rafaelfranca** [comment]
Agree this seems like to wrong place to do it.

This post install message would have the opposite effect to me. Because it is annoying, I'd not contribute to the project.

**Comment by indirect** [comment]
@rafaelfranca if the companies that use ~$40k/mo worth of servers and ~$20k/mo worth of dev time had agreed to join when we reached out to them directly, we wouldn't be adding this message. But almost all of those companies told us they weren't interested in helping keep RubyGems running, so here we are.

@hmistry I'll tweak the wording to remove references to profitability so that we can ship something that isn't contentious. Later on maybe we can get a version that's been tuned by the marketing team. 👍

**Comment by hmistry** [comment]
@indirect I'm happy with that. Thank you for reconsidering.

**Comment by hmistry** [comment]
@indirect Posting here so we can refer back in future. 

Here are more messages that ask for companies (or call it businesses) instead of individuals. From a marketing perspective, this is going to be mostly an awareness campaign to developers. I wouldn't expect any strong leads from it because it's not the business decision makers that will be seeing this message. It's going to be up to the developers to bring it up with their management. If you want to make this more effective, you'd want to create a different landing page that's tailored to helping these developers presenting a good case to the company decision makers... more work, I know but that's how to make it more effective.

Messages:

Bundler and RubyGems.org are free for anyone to use, but maintaining them costs more than $20,000 USD every month. We are looking for company sponsorships to help us cover those costs so we can keep the gem ecosystem free for everyone: https://rubytogether.org/join

We need your help. It costs Ruby Together a minimum of US$20,000 per month to maintain Bundler and RubyGems.org. Ask your company if they would like to help us cover the costs by joining for as little as $50/month at https://rubytogether.org/join and let's keep the gem ecosystem free for everyone.

We need your help. It costs Ruby Together a minimum of US$20,000 per month to maintain Bundler and RubyGems.org. We are looking for companies to help us cover the costs by joining for as little as $50/month at https://rubytogether.org/join. Let's keep the gem ecosystem alive and free for everyone so we can all benefit from open source gems.

**Comment by jeffnyman** [comment]
I realize this is closed, but speaking as a consultant, I've seen at least two companies in Chicago literally drop plans for using Ruby (mainly for their test ecosystem, not so much for core development) because of these messages.

The concern was that RubyGems and Bundler are "in trouble" or eventually will be.

I'm just throwing this out there as an (admittedly very limited) data point. But I'm also hearing more talk of this in various test forums as well, where testers are being asked to move to "healthier" ecosystems, like JavaScript or Python and, at least if what I'm being told is accurate, it's due to the perception of "trouble" and a perception that parts of the ecosystem may "stop working" if money doesn't roll in.

**Comment by indirect** [comment]
@jeffnyman it's a tough conundrum. If we don't tell people that it's expensive to run the service, no one will help fund it, and it will collapse. If we do tell people it's expensive to run the service, lots of people will help fund it, and we'll be fine.

A small amount of research into the ecosystems around these languages would go a long way, I think. Ruby Together _is_ funded well enough to sustain the RubyGems ecosystem right now... the reason we're talking about this is because it is still growing, quickly. Python, on the other hand, has publicly discussed how they don't actively have anyone taking care of this problem in their ecosystem, even though the problem is present there as well. As for JavaScript, maybe you should suggest that your clients check out the many millions of dollars that NPM has raised, and their recent round of layoffs.

Ultimately, we can't make everybody happy. We may be able to word the message in a less alarming way, but I think that message is the best chance we have of escaping the situation that Ruby and Python and JavaScript are all trapped in, in the long run.
