### ISSUE TITLE
Bundler 1.14.x fails on read only docker root

### ISSUE THREAD

**Issue by jlambert121** [bundler/bundler#5371]
We run our production rails apps with the `--read-only` flag when launching our containers, but bundler 1.14.0 broke the ability to run without a r/w temp space.  It looks like the source of this came with this PR:  https://github.com/bundler/bundler/pull/4951

```
$ docker run -it --rm --read-only -e DEBUG=true <container> bundle exec puma -C config/puma.rb
/usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:169:in `rescue in user_home': Your home directory is not set properly: (RuntimeError)
* `/root` is not writable

Bundler also failed to create a temporary home directory at `/tmp/bundler/home/unknown`:
There was an error accessing `/tmp/bundler/home/unknown`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir - /tmp/bundler
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:163:in `user_home'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:180:in `user_bundle_path'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/settings.rb:287:in `global_config_file'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/settings.rb:49:in `initialize'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:243:in `new'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:243:in `settings'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/env.rb:32:in `report'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:95:in `request_issue_report_for'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:45:in `log_error'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
 from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
 from /usr/local/bundle/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
 from /usr/local/bundle/bin/bundle:22:in `load'
 from /usr/local/bundle/bin/bundle:22:in `<main>'
```

Is this an intended side effect?

**Comment by segiddins** [comment]
Why isn't your users home directory writable either? Writing to the tmpdir is only a fallback in that case

**Comment by jlambert121** [comment]
This is in a docker container launched with the `--read-only` flag meaning the entire FS is read only.

**Comment by segiddins** [comment]
Ah so in that case bundler should ignore that exception when it's fetching the global config

**Comment by jlambert121** [comment]
Yeah.  Dependencies should already be installed/configured when the container itself is built so it shouldn't need any tmp space.

**Comment by davetron5000** [comment]
I think it's [this change](https://github.com/bundler/bundler/pull/4951/files#diff-5c7df1d541890e819d15c4646567e69aL64).  Before, bundler would call into [`Bundler.rubygems.user_home`](https://github.com/bundler/bundler/blob/master/lib/bundler/rubygems_integration.rb#L138), which does not write to the filesystem, just returns the value.

The change added in the referenced PR changes it so that `Bundler.user_home` writes directories.

In particular [this discussion](https://github.com/bundler/bundler/pull/4951/files#diff-f16005c816b041d780fe456efcfb3a62L101) seems relevant and is likely why @indirect was bring up the issue.

I think we could solve this by removing [this line](https://github.com/bundler/bundler/pull/4951/files#diff-f51589bbb809dbcf630797a79ef32bedR171) entirely, but I have no idea how easy that is going to be to test.

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/5421 is another option to fix this
