### ISSUE TITLE
Gem Load Error is: uninitialized constant Timeout::Error

### ISSUE THREAD

**Issue by phspies** [bundler/bundler#5582]
When using bundler 1.14.6, I get the following error:

`/.rvm/gems/ruby-2.2.3/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mysql2'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Timeout::Error
Backtrace for gem load error is:
`

This error disappears when downgrading to 1.14.4....

**Comment by segiddins** [comment]
This sounds like a bug in the `mysql2` gem not `require "timeout"` before referring to the constant

**Comment by steventwheeler** [comment]
I have also encountered this error. The error starts with bundler v1.14.5. My application had been using v1.13.7 with no issues. I stepped up through all of the non-pre versions on rubygems.org until I reached v1.14.5 which broke my application. It seems happens when loading any gem which uses `Timeout::Error`. I have seen it with both mysql2 and rollbar. I even tried explicitly requiring `timeout` in my Rakefile without any luck.

**Comment by steventwheeler** [comment]
I have created a demo repository which can be used to reproduce this in v1.14.5 and v1.14.6.

[steventwheeler/bundler_bug_5582](https://github.com/steventwheeler/bundler_bug_5582)

**Comment by segiddins** [comment]
You need to require timeout if your code is using it, the fact an old version of bundler might have done so was a coincidence that you can't depend upon. I'm sorry for the hassle.

**Comment by steventwheeler** [comment]
The test code does require timeout.

From [lib/test.rb](https://github.com/steventwheeler/bundler_bug_5582/blob/master/lib/test.rb#L1)
```ruby
require 'timeout'

raise Timeout::Error, 'This is a test'
```

**Comment by segiddins** [comment]
This appears to be because the `timeout` gem has its own `timeout.rb` file that `require "timeout"` is requiring instead of the stdlib file
