### ISSUE TITLE
Striving for a lighter Ruby on Rails Docker image with the builder pattern and bundler

### ISSUE THREAD

**Issue by MrOutis** [bundler/bundler#5663]
Recently, I found about the **builder pattern** in Docker:

> A workaround (for having huge images) which is informally called the builder pattern involves using two Docker images - one to perform a build and another to **ship the results** of the first build **without the penalty of the build-chain and tooling** in the first image.

I was wondering if this can be achieved with Ruby and bundler, and tried the above:

Builder image:
```dockerfile
FROM ruby:2.4.1-alpine

ENV RAILS_ENV production
ENV RACK_ENV production
ENV LANG C.UTF-8

RUN \
  apk update && \
  apk upgrade && \
  apk add --no-cache \
  build-base \
  bash \
  git \
  less \
  tzdata \
  postgresql-dev \
  mysql-dev \
  sqlite \
  nodejs

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
```

And executed something like:
`docker run -v "${PWD}:/usr/src/app" build-rails bundle install && bundle package --all`

Bundler created a `vendor/cache`, and used the following "production" image:
```dockerfile
FROM ruby:2.4.1-alpine

ENV RAILS_ENV production
ENV RACK_ENV production
ENV LANG C.UTF-8

EXPOSE 3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN chown -R nobody:nogroup /usr/src/app
USER nobody

CMD ["rails", "server", "-b", "0.0.0.0"]
```

when I did `bundle install --without development test`,  everything was green and working like charm...

```ruby
Installing rack 2.0.1
Installing nio4r 2.0.0 with native extensions
Installing websocket-extensions 0.1.2
Installing mime-types-data 3.2016.0521
...
```
but suddenly:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/nio4r-2.0.0/ext/nio4r
/usr/local/bin/ruby -r ./siteconf20170514-18-1wgwy7o.rb extconf.rb
checking for unistd.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers
```

I guess I don't understand bundler enough:
- `vendor/cache` stores the already compiled gems?
- should I also copy the `/usr/local/bundle/bin` ?
- is it possible to roll out a packaged version (somehow) of a Rails project, in a similar way to Java jars?

**Comment by mcmire** [comment]
I think this is more of a Docker question than a Bundler question, but here goes.

First, I've never heard of using two Dockerfiles in the way that you describe. I was expecting that you would publish two images and have the second Dockerfile depend on the image created by the first. I am bit puzzled by the approach you've taken.

Maybe there are some details you didn't mention, but I don't think what you think is happening is what's actually happening. `docker run` will make a new container from the given image. Due to Docker's filesystem layering, any changes you make to the filesystem will be sandboxed within that container. If you run `docker run` again, then those changes will disappear and you'll start over from the image. So when you ran `bundle install` the second time, it likely did not use any of the gems that you installed the first time around.

You could get around this by using Docker Compose to mount `vendor/cache` as a volume -- that way it will persistent between different containers. However, I wouldn't do that...

> is it possible to roll out a packaged version (somehow) of a Rails project, in a similar way to Java jars?

Yes -- the answer is to run `bundle install` inside of your Dockerfile so that your image has everything necessary for your Rails app to run in production. (You'll also want to precompile assets, install JavaScript dependencies, etc.) This way all you have to do on your own server is pull down the image and run it, and it should just work.

If you need any more help with this, let me know.

**Comment by MrOutis** [comment]
Thank you, @mcmire, the reason for this was to not install build dependencies in the final Docker image (to make it slimmer, leaving just the runtime deps). At first I wanted to create a tar (somehow) of the compiled gems and add it to the final version `ADD gems.tar /usr/local/bundle`, but at the end I did something like:

```dockerfile
RUN apk add --virtual build \
    git build-essentials and more packages \
    && bundle install --without dev and test \
    && apk del buil
```

This way, I can build my gems and delete the build environment in the same layer.

I will close this issue, as is not relevant for me anymore.

**Comment by dmitrym0** [comment]
I think this issue is still relevant, especially now that the "build pattern" is officially supported as [multi stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).

I'd like to see if there's a way to grab an existing gem directory to export it from a *build* image to a *runtime* image. I've been poking around my $GEM_HOME. There's a directory for a gem called Nokogumbo. It weighs in at 166 megs, with 160megs of it being taken up by an `ext` directory which I assume contains artifacts from building a native extension (bunch of `*.o` files). 

I guess what I want to know is:

1. Can I get rid of all non-essential files?
2. Can I cleanly export this directory from my build image, into my runtime one?

**Comment by dmitrym0** [comment]
Some further thoughts on this:

I did a 

    bundle install --deployment --path ~/asdf --without development test

then in `~/asdf`:

```
~/a/r/2.3.0 ❯❯❯ du -sh                                                                                                                                                                                                                   
655M
```

Then a 

    find . -iname '*.o' -exec rm {} \;
    find . -iname '*.a' -exec rm {} \;

and 

```
~/a/r/2.3.0 ❯❯❯ du -sh
351M	.
```

That's 300 megs or about 45% savings, just by deleting object files. Is there a `gem remove-native-extensions-build-artifacts` that I'm not seeing?

**Comment by t-anjan** [comment]
This article has information for what is being asked in this issue: https://www.georg-ledermann.de/blog/2018/04/19/dockerize-rails-the-lean-way/
