### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liujiangbo1** [bundler/bundler#5970]
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

**Comment by colby-swandale** [comment]
Sorry that you're having a problem with Bundler. Unfortunately the information that you have provided isn't enough for us to tell what went wrong, or how to fix it. Please follow the instructions in [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) and report back, so that we can try to help.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
