### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by pasanrox** [bundler/bundler#6210]
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'

this line is in my gem file .

In the terminal whern i run bundle install
it gives me errors

No such file or directory  git clone https://github.com/codehale/bcrypt-ruby.git

**Comment by colby-swandale** [comment]
Hi, can you please copy/paste the error report that Bundler is printing.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by XavierDD1st** [comment]
I am having the same problem. 
`gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'`
`Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C
:/Ruby24-x64/lib/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da44
73665a7f096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet`
due to error (2/4): Errno::ENOENT No such file or directory - git cl
one "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby24-x64/lib
/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd
4a2b44229a6546ff6af" --bare --no-hardlinks --quiet

Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C
:/Ruby24-x64/lib/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da44
73665a7f096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet`
due to error (3/4): Errno::ENOENT No such file or directory - git cl
one "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby24-x64/lib
/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd
4a2b44229a6546ff6af" --bare --no-hardlinks --quiet
Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C
:/Ruby24-x64/lib/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da44
73665a7f096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet`
due to error (4/4): Errno::ENOENT No such file or directory - git cl
one "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby24-x64/lib
/ruby/gems/2.4.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd
4a2b44229a6546ff6af" --bare --no-hardlinks --quiet`
