### ISSUE TITLE
Merge /doc/README.md with /doc/contributing/README.md

### ISSUE THREAD

**Issue by rubymorillo** [bundler/bundler#6321]
Hi team!

One of our goals in Ruby Together is of ongoing maintenance of the Bundler docs. To that end, I've already made a few modest changes to the /doc/contributing/README.md doc and of course, to the main Bundler README.

Part of these ongoing maintenance efforts is trying to cut down on places where we have duplicate content. Going through the files we have in /docs/, I realized that the [/doc/README.md](https://github.com/bundler/bundler/blob/master/doc/README.md) file and the [/doc/contributing/README.md](https://github.com/bundler/bundler/blob/master/doc/contributing/README.md) doc serve the same function: guidelines for onboarding potential contributors. The only minor differences between these two files are a link or two that's listed in the /doc/README.md that isn't present in the /doc/contributing/README.md. 

(A thing to note is that there are still instances of duplicate content within these folders, but the READMEs make the most sense to start with since contributors will likely look at that content before going into another file.) 

What I propose is moving the recently updated /doc/contributing/README.md out of the /contributing/ folder and turning it into the main /doc/README.md file. Should we want to keep a link or two currently listed in the /doc/README, we can easily add it into the updated file. 

I'm assigning myself to this issue for now but would absolutely appreciate feedback from the team if anyone has any suggestions!

cc @indirect @hmistry @colby-swandale

**Comment by hmistry** [comment]
Quick feedback:
1. It's hard to judge which links are common and which are missing between the 2 documents. Maybe if you can spell that out more, it'd be easier to comment on to answer your question.
2. Regarding merging them, generally I'm for it. My knee-jerk reaction says the /doc/Readme is more encompassing than /doc/contributing/readme... so maybe transfer missing things upwards?
3. The Readme's in each `/contributing, /documentation, /development` folders seem to serve a purpose in the event some one navigates to that folder through files and not through readme guides. So knee-jerk reaction is those readme's should stay and explain the content in that folder and direct users to the higher level if they are looking for a different category like dev or documentation.
4. With that said, there's something really bothering me about this whole division of contributing, development, and documentation. I finally understand what - it's that the last 2 are a subset of contributing and not having this hierarchy is causing some overlaps between the sections because you can't talk of contributing without dev or documentation. What if we create a different hierarchy like:
```
Contributing (or /doc?):
- Overview and general stuff e.g. getting started
- Issues stuff
- Development stuff
- Documentation stuff
- Getting help and community
```
What do you think?

**Comment by indirect** [comment]
I think merging is a good idea! My hope is that eventually the main readme will explain what this is, and direct end users to the docs site at bundler.io so they can learn about bundler, and redirect interested contributors to /doc/README.md where we will have internally-facing documentation. This seems like a good step in that direction.

**Comment by rubymorillo** [comment]
@hmistry great ideas! So we should definitely maintain READMEs in all of those folders, we just need to be more clear about what content should be in them, and always link back to the main Contributor Guidelines from each in case users want/need to access it. I'll keep that in mind when coming up with an outline!

@indirect good to know! I'll start brainstorming an outline for what all of this could potentially look like and will add it in a gist :).

**Comment by hmistry** [comment]
@rubymorillo Actually on second thought, I don't know if there's much value in having readme's in each of those folders, as long as there's a good well explained one in the base folder linking to them. Maybe it just needs a link back?? 
Let's see what you come up with and what makes sense for the 2 types of users (gem developers and gem users seeking help) because there's a cost to maintaining all these readme's too. Perhaps @indirect's vision of directing some things to the website will help simplify things.

**Comment by rubymorillo** [comment]
@hmistry @indirect I haven't made much headway with this lately because of school, but looking at both files, I'm open to @hmistry's suggestion that we make the [/doc/contributing/README.md](https://github.com/bundler/bundler/blob/master/doc/contributing/README.md) the _main_ README, replacing [/doc/README.md](https://github.com/bundler/bundler/blob/master/doc/README.md).

If we do this, should I also delete a README in the Contributing folder, or should we turn that README into a "Table of Contents" that basically lists out the different files in the Contributing folder, with a sentence-long description?

**Comment by rubymorillo** [comment]
ping @hmistry @indirect let me know if y'all have any thoughts; if needed, we can table this discussion for now
