### ISSUE TITLE
ArgumentError: Valid types are [:development, :runtime], not nil

### ISSUE THREAD

**Issue by petebrowne** [bundler/bundler#640]
I get the following error when trying to boot a Rail 3 application using Passenger:

```
ArgumentError: Valid types are [:development, :runtime], not nil
/usr/local/lib/site_ruby/1.8/rubygems/dependency.rb:52:in `initialize'
```

Full backtrace: http://gist.github.com/559776

I have tried `bundle update` and removing Gemfile.lock and running `bundle install`.

I'm using:
Rails: 3.0.0
Bundler: 1.0.0
Passenger: 2.2.15

**Comment by ggriffin** [comment]
Just in case anyone else is stuck maintaining some very old code...
For us, this ended up being a mismatch between rubygems and bundler versions. The version of bundler expected this signature from Gem::Dependency, introduced in v1.3.6:
`def initialize name, *requirements`
but we were on v1.3.5 with the following signature:
`def initialize(name, version_requirements, type=:runtime)`
Calling `Gem::Dependency.new(base.first.name, *reqs)` expanded the reqs array into a set of arguments. So, for example, `reqs = ["= 0.8.7", "0.8.7"]` caused `type` to be set to `'0.8.7'`, rather than a valid group type. The error was not terribly helpful b/c the instance value for `@type` was output, rather than the value passed in for `type`. It was straight forward to temporarily hack the code to get better information.

**Comment by indirect** [comment]
@ggriffin thanks for following up! For the record, Bundler has never, ever supported RubyGems 1.3.5. Bundler 1.0.0 launched with support for RubyGems 1.3.6 and higher, and that is what we still support today. 👍
