### ISSUE TITLE
Bundler ignores settings in .gemrc

### ISSUE THREAD

**Issue by qubitrenegade** [bundler/bundler#6633]
# Summary

I can't get bundler to honor my gem sources configured with `gem sources`.

# Steps to reproduce

```
# Set bundler to non-standard source:
$ rm -f ~/.gemrc
$ gem sources --add https://my.gem.mirror

# Create a gem
$ bundler gem test_sources

# Run bundle install
$ cd test_sources
$ bundle install
Fetching gem metadata from https://rubygems.org/
```

# Expected outcome

Bundler should install gems from `https://my.gem.mirror`

I think this issue, #1009, from several years ago says that .gemrc settings should be honored.

Conversely, for environments where you might be behind a corporate firewall, etc. it would be extremely beneficial for bundler to not ignore my .gemrc settings, since many places use tools like Artifactory to provide a sort of "proxy" to rubygems.org.

Thanks!

**Comment by indirect** [comment]
Bundler is (so far) a completely different program from RubyGems, and does a similar but different thing. The person saying Bundler "should" honor .gemrc in #1009 is not a member of the Bundler team, and was offering his opinion, just like you are here.

This is not a valid bug report, because Bundler has never read the .gemrc file to configure itself. If you'd like to rewrite this ticket as a feature request, we're willing to consider it.

Thanks!

**Comment by qubitrenegade** [comment]
Hi @indirect 

Well that is an entirely fair and reasonable suggestion, I think I will do that.  :+1: 

Also, thanks for the education, I guess I've been conflating projects for years since I've had it in my head that gem and bundler were related.  My apologies :)

Q
