### ISSUE TITLE
Bundle Install generating Carriage Returns

### ISSUE THREAD

**Issue by austinh** [bundler/bundler#6699]
Hello I have recently started noticing that running bundle install on my repo cause new line carriage returns and I'm not sure why.

`Bundler version 1.16.2`
`Mac OS X 10.13.6`
`ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]`
tested with `iTerm2` and standard OS X `Terminal`

screenshot of git diff before and after `bundle install`: 

![image](https://user-images.githubusercontent.com/659239/45524471-affa5580-b79c-11e8-890c-c7584c67e79d.png)

I can also get this to happen in docker as well on the same mac. Docker running alpine linux with ruby in it and doing bundle install cause these carriage returns to replace new lines and to annoyingly take up history and stash changes for all engineers. (This is happening across)

Any idea why this is happening? Is it a setting?

**Comment by colby-swandale** [comment]
We will need an example Gemfile and Gemfile.lock to help us debug this issue

**Comment by deivid-rodriguez** [comment]
I'm guessing it could be related to the latest encoding fixes. Can you try with latest bundler (1..16.4)?

**Comment by austinh** [comment]
I tried with bundler 1.16.4 and same issue occurs. However, I am noticing this only happens on a single repository. I can't get it to happen on other repositories. And unfortunately the repo that this happens on is a private repo for work. I can repeat it on 4 other developers machines though. I wonder if theres some sort of setting thats causing this to happen? Maybe even at the git level - its possible its not a problem with bundler. Although it doesnt happen on `git add` - it happens before any git actions are taken - just by runnig bundle install.

**Comment by greysteil** [comment]
OK, sounds to me like this is pretty unlikely to be Bundler related, so I'm going to close this, but I'd still like to get to the bottom of it.

My hunch is that the issue here is going to be a post-install script, or a plugin, especially as it was initially surfaced by Dependabot not creating the carriage returns (which would make sense, as Dependabot doesn't actually do an install).

@austinh - let's take this offline. I think the next step in diagnosing it is to bisect your Gemfile, and see if it's a particular gem that's causing this.
