### ISSUE TITLE
`bundler check` outputs warning about platform not used 

### ISSUE THREAD

**Issue by y-yagi** [bundler/bundler#6724]
Hi

In Bundler v1.16.6, `bundler check` outputs a warning about platform not use. This was not output until v.1.16.5.  

```
# Gemfile 
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby] 
```  

**Bundler 1.16.6** 

``` 
$ bundler -v
Bundler version 1.16.6
$ bundle check
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
The Gemfile's dependencies are satisfied 
``` 

**Bundler 1.16.5**  

``` 
$ bundler -v
Bundler version 1.16.5
$ bundle check
The Gemfile's dependencies are satisfied 
``` 

The command was executed on Linux. Is this intentional change? 

Thanks!

**Comment by deivid-rodriguez** [comment]
@y-yagi I think this is due to https://github.com/bundler/bundler/pull/6495. That bug fix didn't explicitly intend to change this behavior, but the change was a side-effect of it? I would argue though that the new behavior is what we want. /cc @segiddins 

Note that you can:

* Add the missing platforms to the lockfile with the suggested command.
* Disable these warnings with (from `bundle config --help`)

> **disable_platform_warnings** (**BUNDLE_DISABLE_PLATFORM_WARNINGS**): Disable warnings during bundle install when a dependency is unused on the current platform.

We should update that text to reflect the current behavior if we decide it's what we want by the way.

**Comment by y-yagi** [comment]
I was curious that there was no mention of this change in the release notes(https://github.com/bundler/bundler/releases/tag/v1.16.6). 
There is no objection on the change itself. Thank you for the detailed explanation!
