### ISSUE TITLE
warning about older lockfile version should follow Semantic Versioning conventions

### ISSUE THREAD

**Issue by ColinDKelley** [bundler/bundler#6731]
We get warnings like this on `bundle install` in our repo:
```
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```
I think `Bundler` should respect Semantic Versioning with the `Gemfile.lock` format being akin to an API.  SemVer says that changes in the third segment are patches and "Bug fixes not affecting the API increment the patch version".  So any 1.16.* version should work with files written by other 1.16.* versions.

LMK if this sounds good and I'll create a PR.

**Comment by deivid-rodriguez** [comment]
You could made that same argument to recommend never committing in your `Gemfile.lock` and instead use "semver compliant" operators in your `Gemfile`. However, the point `bundler` tries to achieve by locking in all your dependencies is to ensure that your environment is deterministically reproducible everywhere. `bundler` is another dependency of your application (just a bit special), so we believe locking it as well is good to ensure reproducibility across environments.

**Comment by greysteil** [comment]
It's worth adding that Bundler *does* try to respect Semantic Versioning with the `Gemfile.lock`, and does a pretty good job of it.

We're not perfect, however, and have accidentally changed the order of git dependencies as they appear in it in the past (for example). As a result I think it's probably wise that we continue to advise teams to all be on the same version of Bundler, but perhaps we could add something to the message saying it's just a precaution if the delta isn't a major version? Something like adding `Whilst every effort is made to ensure the `Gemfile.lock` is backwards compatible across minor and patch versions we suggest...`.

**Comment by deivid-rodriguez** [comment]
Yeah, I was going to say that I'm against removing the warning that advices full locking, but maybe we could allow people to disable it for patch level versions or tweak the wording.

**Comment by ColinDKelley** [comment]
@deivid-rodriguez:
> so we believe locking it as well is good to ensure reproducibility across environments.

Yes, I wasn't arguing against locking it. My point was that the file format for all versions 1.16.* (for example) should be compatible with each other. I believe this has been true in practice. And I believe that SemVer says it should always be true, assuming external file formats can be viewed as an "API":
"Bug fixes not affecting the [Gemfile.lock format] increment [only] the patch version".

**Comment by deivid-rodriguez** [comment]
Yeah, I get what you're saying and it is indeed true in practice. But the running version of bundler does not only affect the lockfile format, but can affect other things too. The idea is that the code belonging to bundler that gets run when you run any bundler command inside the application is always the same and does not vary from one developer to another or from one environment to another. At least that's how I understand the introduction of `BUNDLED_WITH` and the associated warnings.

**Comment by ColinDKelley** [comment]
> code belonging to bundler that gets run when you run any bundler command inside the application is always the same and does not vary from one developer to another or from one environment to another

Yes, that parallels APIs and gems and other programming interfaces that are versioned. But it's not expected that the code is byte-for-byte identical. What matters is the interface contract, and the version number conveys that. Breaking changes bump the major version. Enhancements that add new features but don't break anything bump the minor version. Patches that have no effect on the contract bump the patch version.

It's the last point that's not currently coded in Bundler. I'd like to add it, so that, for example, any version written by the `1.16.*` range is considered compatible with other `1.16.*` versions and doesn't issue a warning about upgrading. Make sense?

**Comment by deivid-rodriguez** [comment]
I see what you're saying, but in my opinion these are two different issues.

* One thing is semantic versioning and the _expected_ compatibility policy of each library. This is useful, for example, when upgrading a library since it informs users about what to expect when they upgrade.
* Something else is version locking and _real life_. This ensures that the environment is byte per byte the same for all environments and all developers of the application.

For example, say dependency "x" releases 1.17.1. Semantic versioning tells us that this is a safe upgrade, and if anything, it will fix bugs on top of 1.17.0. Your application could theoretically add `~> 1.17.0` to the `Gemfile`, don't commit the lock file, and be happy. Imagine though, that this upgrade accidentally causes an incompatibility with your application due to a subtle bug. Without committing the lock file, it's going to be harder to debug because some developers will hit the bug, others won't, and it's uncertain when it will hit production. This is what the lock file is for, and why it's recommended to commit it.

This would be a similar thing but regarding `bundler` itself, instead of library "x".

Whether this warning should be on or off by default, or disableable for semver compatible versions, or whatever is another story (for example, `bundler` does not warn you when you don't commit your lock file). I would be in favor of making this warning configurable, but I wouldn't like to see the "bundler not fully locked" warning just go.

**Comment by ColinDKelley** [comment]
Now I follow your argument of equivalence.  We both agree that the `Gemfile.lock` was a brilliant idea to make sure that "believed to be compatible" versions don't drift into usage and accidentally break things at the worst time. An example like that could be a gem that formerly silently ignored an unsupported `nil` value for an argument and in a patch release it added an assertion that a non-nil value must be passed. A caller might have been passing `nil` the whole time and suddenly can't use the gem when that patch version increments.

Examples like the above come up because it's difficult to document the full contract of all interfaces. For example, in many cases the answer to the question "what happens if I pass `nil` here?" is "I don't know--try it". (Ruby's 20 years old and still, most methods don't document their behavior when passed `nil`!)

But fortunately we're not talking about the difficulty of documenting contracts across arbitrary software components. We're talking about compatibility of a file format written by the same software component--`bundler`. We can know when we change the semantics of the file format--and we do that infrequently. We can easily test its compatibility when we're not sure.

And in any case, SemVer says that the version *must* represent our best understanding of compatibility, and gives us 3 version numbers to do that with. If we believe it's compatible, we bump the patch version. If we add behavior that adds new semantics that might not be compatible in some way, we bump the minor version. If we change the format in a way we know is not compatible, we bump the major version. SemVer gives us all the tools we need. Your concerns can be met while complying with SemVer:  just bump the minor version more frequently.

**Comment by deivid-rodriguez** [comment]
I think the barrier we're having to fully understand each other is that we interpret the `BUNDLED_WITH` version in the lock file differently. Whereas you interpret it as "the version of the current format of the lock file", I interpret it as "the current version of bundler the application is 100% guaranteed to work". Maybe the right interpretation is yours, I'm not sure.

In my opinion, this is not only about the lockfile format, but about the whole bundler library & CLI. For example, it could happen that an application is using some combination of bundler environment variables and CLI flags that work under one version, but prevent the application from booting, or make some bundler subprocess crash under the next patch level version of bundler. It's unintended, we'd never want that to happen, but fully locking the version of bundler an application uses gives us determinism in that regard.

**Comment by ColinDKelley** [comment]
> I interpret it as "the current version of bundler the application is 100% guaranteed to work". 

Right, I agree that we differ in that perspective. I'm advocating that we follow SemVer. Are you saying that SemVer requires "100% guaranteed to work" compatibility? Or rather are you advocating that Bundler "do better" than SemVer requires?

**Comment by deivid-rodriguez** [comment]
We're trying to follow semver as closely as possible when it comes to releasing versions of bundler. I'm saying that the presence, wording and toggleability of this specific warning is part of a separate discussion. And I _personally_ would accept a feature that allows end users to disable this warning, either fully or for semver compatible versions.

**Comment by deivid-rodriguez** [comment]
> Are you saying that SemVer requires "100% guaranteed to work" compatibility? Or rather are you advocating that Bundler "do better" than SemVer requires?

I'm so sorry we're having to trouble understanding each other. These questions definitely show that I'm not making myself understood... :disappointed: 

I'm going to let other maintainers handle this since I'm failing to communicate properly my vision. 

Thanks for volunteering for making any changes to bundler you believe are correct, by the way :heart:.

**Comment by ColinDKelley** [comment]
Ok! I'll send a PR (hopefully tomorrow) and at least that will give everyone something concrete to consider. If it winds up behind a configuration flag, that's fine.

**Comment by indirect** [comment]
Hi @ColinDKelley! Thanks for opening this issue. Your original post seems to be asking for two completely separate things:

1) The `Gemfile.lock` generated by 1.x should be compatible with any 1.x.y version
2) Bundler should not print a warning if you are running a 1.x.y where `y` is lower than the version of Bundler that created the lockfile.

Those are two completely separate, and unrelated, issues, so I'm going to address them separately.

For issue 1), I can confirm that the `Gemfile.lock` format is absolutely compatible across an entire major version of Bundler. A lockfile that works with Bundler 1.14 will also work with 1.16, etc. While that same lockfile may not cause an error, it still may not produce exactly the same results in both 1.14 and 1.16, because we regularly fix bugs in the way that Bundler finds gems and installs them.

Moving on to issue 2), the warning message that you are describing in your original post: that message has nothing to do with lockfile compatibility. The entire purpose of the warning is to let you know that you might not get the same results as the person who created that lockfile, and to suggest that you update to the exact same version of Bundler in order to guarantee that you will get the same results.

We think it's a useful warning, because of many past tickets that have turned out to be issues caused by different developers using different versions of Bundler on the same project. The message is completely accurate: we, the Bundler team, recommend that everyone upgrade to the same version of Bundler as the version that created the lockfile, so that everyone will see exactly the same results.

**Comment by colby-swandale** [comment]
This seems answered
