### ISSUE TITLE
bundle exec not working with gem from git

### ISSUE THREAD

**Issue by mwpastore** [bundler/bundler#6732]
I'm experiencing some very strange behavior trying to `bundle exec` with a gem ([Sequel](https://rubygems.org/gems/sequel), specifically) from [git](https://github.com/jeremyevans/sequel). When I go the bundler/setup route without `bundle exec`, it works fine. When I use the published version of the gem, it works fine. I am so very confused.

With or without the trailing .git, with or without a local override, with https or with the git protocol, with or without a ref, doesn't seem to matter.

Platform: Darwin (macOS 10.14 Mojave)
Bundler: 1.16.6
Ruby: 2.5.1
rbenv: 1.1.1

### Contents of `Gemfile`:

```rb
source 'https://rubygems.org'

gem 'sequel', git: 'https://github.com/jeremyevans/sequel.git'
```

### Output of `bundle up`:

```
Fetching https://github.com/jeremyevans/sequel
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.16.6
Using sequel 5.13.0 from https://github.com/jeremyevans/sequel (at master@8b6f117)
Bundle updated!
```

### Contents of `Gemfile.lock`:

```
GIT
  remote: https://github.com/jeremyevans/sequel
  revision: 8b6f117ff47ff8c28f0b952cc20a07300b9f2ecb
  specs:
    sequel (5.13.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  sequel!

BUNDLED WITH
   1.16.6
```

### Output of `bundle exec ruby -r pp -e 'pp $LOAD_PATH'`:

```json
["/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib",
 "/usr/local/Cellar/rbenv/1.1.1/rbenv.d/exec/gem-rehash",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/sequel-8b6f117ff47f/lib",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/x86_64-darwin17",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby/2.5.0/x86_64-darwin17",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/x86_64-darwin17"]
```

### Output of `bundle exec ruby -r sequel -e 'puts Sequel.version'`:

```
Traceback (most recent call last):
	1: from /Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- sequel (LoadError)
```

### Output of `ruby -r bundler/setup -r pp -e 'pp $LOAD_PATH'`:

```json
["/usr/local/Cellar/rbenv/1.1.1/rbenv.d/exec/gem-rehash",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/sequel-8b6f117ff47f/lib",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/x86_64-darwin17",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/site_ruby",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby/2.5.0/x86_64-darwin17",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/vendor_ruby",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0",
 "/Users/mwp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/x86_64-darwin17"]
```

### Output of `ruby -r bundler/setup -r sequel -e 'puts Sequel.version'`:

```
5.13.0
```

**Comment by mwpastore** [comment]
I was able to confirm it with a different gem (rack), so it's not specific to Sequel.

**Comment by colby-swandale** [comment]
This is happening because of how Git gems in Bundler work and how Ruby handles loading libraries via the `RUBYOPT` option and the `-r` argument.

If you specify both the `RUBYOPT=-r <library>` option and the `-r <library>` argument (`bundle exec` sets the `RUBYOPT` env var and you're setting the `-r` argument), Ruby will load `-r <library>` first, then the `RUBYOPT=-r` second. This means that the `-r <library>` is being loaded before Bundler.

Unless you're using the `--path` option in `bundle install`, your gems are installed in the same gem repository that RubyGems uses when you run `gem install`. So when Ruby tries to load `-r <library>`, RubyGems will look and see that the gem is installed and can be loaded (This is why loading Rack works). Git gems work a bit differently because they're not actually gems, they're a folder that RubyGems cannot see and something that Bundler needs to configure the `$LOAD_PATH` with before you can load it. This is why you're seeing the `LoadError`

We can't really fix this issue unless Ruby core decides to change the order it uses to load arguments/options. But hopefully this gives you a reason for why this is happening.

**Comment by mwpastore** [comment]
Thank you for the explanation!
