### ISSUE TITLE
Bundler error on Middleman from template 

### ISSUE THREAD

**Issue by k8buxton** [bundler/bundler#6837]
I'm trying to initialise my project and getting some Gem errors (used the same template recently and worked just fine).

This is the content of my Gemfile: 

```ruby
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets'
gem 'middleman-deploy', git: 'https://github.com/lewagon/middleman-deploy.git'
gem 'pry-byebug', require: true

gem 'font-awesome-sass'
gem 'bootstrap-sass'
gem 'jquery-middleman'

gem 'autoprefixer-rails', '~> 6.7.0'
gem 'middleman-core', '~> 4.1.0'
```

I am getting the following error: 

```
Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    middleman-core (~> 4.1.0)
    middleman (~> 4.2) was resolved to 4.3.0.rc.1, which depends on
      middleman-core (= 4.3.0.rc.1)
```

However, when I update to 4.3.0.rc.1 I get even more dependency issues.

I didn't have a Gemfile.lock but have now added one in, and still getting Gem Bundler issues.

**Comment by deivid-rodriguez** [comment]
Hi @k8buxton!

The dependencies you're specifying in your `Gemfile` are incompatible between each other.

* On one hand, you're specifiying `middleman-core  ~> 4.1.0`. That means you want versions equal or higher than `4.1.0`, but lower than `4.2.0`.
* On the other hand, you're specifying `middleman ~> 4.2`. That means versions of `middleman` higher than or equal to `4.2.0`, but lower than `5.0.0`.

Apparently, each version of the `middleman` gem depends on the [exact same version](https://github.com/middleman/middleman/blob/a3db298d59cbee7b9b42abdaa99dead6a10bb660/middleman/middleman.gemspec#L21) of the `middleman-core` gem, so you're esentially requesting `middleman-core` lower than 4.2.0 and higher than 4.2.0 at the same time.

You should be able to fix this by changing the `middleman-core` dependency to `~> 4.2` (instead of `~> 4.1.0`), or even better, remove that dependency altogether, since it's provided by the `middleman` dependency anyways.

Hope this helps!

**Comment by k8buxton** [comment]
Hi Deivid, thank you for your swift response! I have removed the middleman-core gem altogether, so my Gemfile is now:

source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets'
gem 'middleman-deploy', git: 'https://github.com/lewagon/middleman-deploy.git'
gem 'pry-byebug', require: true

gem 'font-awesome-sass'
gem 'bootstrap-sass'
gem 'jquery-middleman'

 However, now when I bundle install I am getting this error: 

Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
You have requested:
  autoprefixer-rails ~> 6.7.0

The bundle currently has autoprefixer-rails locked at 8.6.5.
Try running `bundle update autoprefixer-rails`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`

Then when I add an updated autoprefixer-rails gem, I get: 

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    middleman-autoprefixer (~> 2.7) was resolved to 2.9.0, which depends on
      middleman-core (>= 3.3.3) was resolved to 4.2.1, which depends on
        bundler (~> 1.1)

  Current Bundler version:
    bundler (2.0.0.pre.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.1)', which is required by gem 'middleman-core
(>= 3.3.3)', in any of the sources.

Look forward to hearing your thoughts.

**Comment by deivid-rodriguez** [comment]
Did you try `gem install bundler`? Apparently `middleman-core` depends on `bundler ~> 1.1`, and you're using `bundler 2.0.0.pre.2`, which does not fit that requirement.

`middleman-core` depending on `bundler ~> 1.1` is kind of weird, but that would be a separate question to raise with the maintainers of `middleman-core`.

**Comment by deivid-rodriguez** [comment]
By the way, when you copy error messages or content of files, make sure you wrap it with backticks so it's easier to read. See https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by colby-swandale** [comment]
This seems answered, closing.
