### ISSUE TITLE
Template expander includes extra blank lines

### ISSUE THREAD

**Issue by fulldecent** [bundler/bundler#6859]
Example:

https://github.com/bundler/bundler/blob/27ab011a686cfbd99fdee56362f68b961458f976/lib/bundler/templates/newgem/newgem.gemspec.tt

The generated output will be:

```

lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
...
```

which includes an unnecessary blank line at top.

**Comment by jabawack81** [comment]
apparently, this is already been fixed by this commit: 
https://github.com/bundler/bundler/commit/00fd58eaa69015092ee272c4cb5aa92a5e7ee45c 
but is not yet released

some quick test:
v 1.17.3 (latest released) the empty line is there
v 2.0.0.pre.3 the empty line is there
v 2.0.0.dev (current master branch) the empty line is not there anymore

I hope this is helpfull

**Comment by colby-swandale** [comment]
Thanks @jabawack81 , i will add this to the next path release of Bundler 2
