### ISSUE TITLE
can't use an older bundler version in my Gemfile

### ISSUE THREAD

**Issue by ahorek** [bundler/bundler#6932]
I can't use an older bundler version in my Gemfile, only if Gemfile.lock already exists.

if it's an intentional change in bundler 2.0, feel free to close the issue.

Gemfile
```
gem 'bundler', '~> 1.13'
```

bundle install
```
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.13) x64-mingw32

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.13)' in any of the relevant sources:
  the local ruby installation
```

according to my Gemfile version 1.17.3 should be used
```
*** LOCAL GEMS ***

bundler (2.0.1, default: 1.17.3)
```

**Comment by ashokf458** [comment]
Facing the same problem when older version of bundler is a dependency of one of the other gems. For example, in my case, the issue is with installing pdk. Dependency: blunder ~> 1.15.0.

Even after manual installtion of bundler 1.15.0, the bundle install doesn't resolve the dependency as already installed. - I am a newbee at using Bundler, so i am not sure, why bundle install command needs to be more complicated than get all dependencies and group by name and version(which Gemfile.lock is) and just gem install them all.

Also, if i try to use bundler 1.17.3, the bundle install fails on finding the dependencies with platform specification. - I thought the gems obtained platform independence through ruby.

**Comment by colby-swandale** [comment]
You have set your Gemfile to require `bundler` with the requirement of `< 2.0` and `>= 1.13`. Running your `bundle install` with Bundler 2 means that this requirement cannot be met. You either need to change your gem requirement to allow for Bundler 2 or fallback to only using Bundler 1 when installing gems.

**Comment by colby-swandale** [comment]
@ashokf458  Can you please open a new issue. See https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md on a guide on what information is helpful for us to help resolve your problem.
