### ISSUE TITLE
osx ruby bundler

### ISSUE THREAD

**Issue by 631068264** [bundler/bundler#6953]
I use `brew` to install ruby
```
ruby --version
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

gem --version
3.0.2

➜  ~ where bundle
/usr/local/opt/ruby/bin/bundle
/usr/local/bin/bundle
➜  ~ which bundle
/usr/local/opt/ruby/bin/bundle

➜  ~ bundle -v
Traceback (most recent call last):
	1: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
/usr/local/opt/ruby/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle (LoadError)
➜  ~ bundler -v
Traceback (most recent call last):
	1: from /usr/local/opt/ruby/bin/bundler:23:in `<main>'
/usr/local/opt/ruby/bin/bundler:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundler (LoadError)

```

➜  gems ll
total 0
drwxr-xr-x  3 wyx  admin   96  2 10 20:21 .
drwxr-xr-x  9 wyx  admin  288  2 10 20:18 ..
drwxr-xr-x  9 wyx  admin  288  2 10 20:18 bundler-2.0.1
➜  gems pwd
/usr/local/lib/ruby/gems/2.6.0/gems

**Comment by ankitkataria** [comment]
Hey @631068264 !
Although, I'm not sure what the actual problem is here, I use [RVM](https://rvm.io/rvm/install) which is a very popular tool for managing local ruby versions. Have you tried it out? 
Here's a comprehensive blog on how to install rvm on osx - https://usabilityetc.com/articles/ruby-on-mac-os-x-with-rvm/ . 
Hope this helps. :slightly_smiling_face:
