### ISSUE TITLE
Update mustermann to 1.1.0

### ISSUE THREAD

**Issue by jeremyevans** [bundler/bundler#7524]
The keyword argument separation issues in mustermann 1.0.3 (which bundler currently uses in tests) are currently blocking the separation of positional and keyword arguments in Ruby 3 development (ruby/ruby#2794). Updating to mustermann 1.1.0 should fix those issues and allow for Ruby 3 development in this area to continue.  Can you please update the tests to use mustermann 1.1.0?

**Comment by kou** [comment]
mustermann 1.1.0 release breaks our CI. See https://github.com/bundler/bundler/pull/7523#issuecomment-569736683

Because we don't pin mustermann version. We just pin sinatra version to '~> 2.0`: https://github.com/bundler/bundler/blob/master/spec/support/rubygems_ext.rb#L22

#7526 will fix the CI failure with mustermann 1.1.0.

**Comment by deivid-rodriguez** [comment]
I'm sorry. We should have better pinning of our test dependencies to avoid this kind of issues. Thanks for fixing this for the time being anyways!

Closing!
