### ISSUE TITLE
Any way to set roles for capistrano bundle:install?

### ISSUE THREAD

**Issue by sdhull** [bundler/bundler#816]
All I can really do is:
    require 'bundler/capistrano'
and
    set :bundle_gemfile,      "Gemfile"
    set :bundle_dir,          File.join(fetch(:shared_path), 'bundle')
    set :bundle_flags,        "--deployment --quiet"
    set :bundle_without,      [:development, :test]
    set :bundle_cmd,          "bundle" # e.g. change to "/opt/ruby/bin/bundle"

But no way to limit it to certain roles.  We have a bunch of different roles defined, and it is inappropriate to run bundle install on all of them....

**Comment by opsidao** [comment]
Was any solution for this implemented?

We use capistrano to deploy several types of apps, and it's not appropiate to run bundle install on all of them, it would be nice if we could specify a set of roles for which this should be run (for example, only in the app role)... 

For the record, we use capistrano 2, so that's also a factor...

Thanks for your time!

**Comment by indirect** [comment]
@opsidao The code built in to Bundler hasn't been touched for years, and we're going to be removing it in Bundler 2.0. I'd recommend copying the tasks out of Bundler and into your deploy files so that you can set roles and do whatever you want.

**Comment by opsidao** [comment]
Thanks for the info @indirect!
